import { Injectable } from '@angular/core';
import { GroupConfigurationView } from '../models/group-configuration-view.model';

@Injectable({
  providedIn: 'root',
})
export class GroupConfigurationViewTestService {
  getDataView(): GroupConfigurationView[] {
    return [
      {
        id: 1,
        tutor: 'María González',
        campus: 'Campus Norte',
        specialty: 'Ingeniería de Software',
        specialtyShortName: 'ISW',
        modality: 'Presencial',
        grade: 'Primer Semestre',
        group: 'A',
        generation: '2023-01-01 / 2023-12-31',
        students: 28,
      },
      {
        id: 2,
        tutor: 'Carlos Ramírez',
        campus: 'Campus Sur',
        specialty: 'Sistemas Computacionales',
        specialtyShortName: 'SIC',
        modality: 'Híbrido',
        grade: 'Segundo Semestre',
        group: 'B',
        generation: '2023-02-15 / 2024-01-30',
        students: 32,
      },
      {
        id: 3,
        tutor: 'Ana López',
        campus: 'Campus Centro',
        specialty: 'Inteligencia Artificial',
        specialtyShortName: 'IIA',
        modality: 'Virtual',
        grade: 'Tercer Semestre',
        group: 'C',
        generation: '2022-08-10 / 2023-07-20',
        students: 25,
      },
      {
        id: 4,
        tutor: 'Roberto Sánchez',
        campus: 'Campus Norte',
        specialty: 'Redes y Telecomunicaciones',
        specialtyShortName: 'RED',
        modality: 'Presencial',
        grade: 'Cuarto Semestre',
        group: 'A',
        generation: '2022-01-15 / 2022-12-15',
        students: 30,
      },
      {
        id: 5,
        tutor: 'Patricia Mendoza',
        campus: 'Campus Oriente',
        specialty: 'Ciberseguridad',
        specialtyShortName: 'CIB',
        modality: 'Híbrido',
        grade: 'Quinto Semestre',
        group: 'D',
        generation: '2022-02-01 / 2023-01-31',
        students: 22,
      },
      {
        id: 6,
        tutor: 'Fernando Torres',
        campus: 'Campus Sur',
        specialty: 'Big Data y Análisis',
        specialtyShortName: 'BDA',
        modality: 'Presencial',
        grade: 'Sexto Semestre',
        group: 'B',
        generation: '2021-08-20 / 2022-07-25',
        students: 27,
      },
      {
        id: 7,
        tutor: 'Gabriela Ruiz',
        campus: 'Campus Poniente',
        specialty: 'Internet de las Cosas',
        specialtyShortName: 'IOT',
        modality: 'Virtual',
        grade: 'Séptimo Semestre',
        group: 'E',
        generation: '2021-01-10 / 2021-12-20',
        students: 18,
      },
      {
        id: 8,
        tutor: 'Héctor Vargas',
        campus: 'Campus Centro',
        specialty: 'Desarrollo Web y Móvil',
        specialtyShortName: 'DWM',
        modality: 'Híbrido',
        grade: 'Octavo Semestre',
        group: 'C',
        generation: '2021-02-05 / 2022-01-25',
        students: 35,
      },
      {
        id: 9,
        tutor: 'Laura Estrada',
        campus: 'Campus Industrial',
        specialty: 'Gestión de Proyectos Informáticos',
        specialtyShortName: 'GPI',
        modality: 'Presencial',
        grade: 'Primer Semestre',
        group: 'F',
        generation: '2023-08-01 / 2024-07-15',
        students: 26,
      },
      {
        id: 10,
        tutor: 'Miguel Álvarez',
        campus: 'Campus Norte',
        specialty: 'Realidad Virtual y Aumentada',
        specialtyShortName: 'VRA',
        modality: 'Presencial',
        grade: 'Segundo Semestre',
        group: 'A',
        generation: '2023-09-01 / 2024-08-10',
        students: 24,
      },
      {
        id: 11,
        tutor: 'Sofía Martínez',
        campus: 'Campus Oriente',
        specialty: 'Computación en la Nube',
        specialtyShortName: 'CCL',
        modality: 'Virtual',
        grade: 'Tercer Semestre',
        group: 'D',
        generation: '2022-08-15 / 2023-07-30',
        students: 29,
      },
      {
        id: 12,
        tutor: 'Javier Morales',
        campus: 'Campus Poniente',
        specialty: 'Robótica y Programación',
        specialtyShortName: 'ROP',
        modality: 'Híbrido',
        grade: 'Cuarto Semestre',
        group: 'E',
        generation: '2022-01-20 / 2022-12-20',
        students: 33,
      },
      {
        id: 13,
        tutor: 'Diana Flores',
        campus: 'Campus Sur',
        specialty: 'E-commerce y Diseño Digital',
        specialtyShortName: 'ECD',
        modality: 'Presencial',
        grade: 'Quinto Semestre',
        group: 'B',
        generation: '2022-02-10 / 2023-01-25',
        students: 31,
      },
      {
        id: 14,
        tutor: 'Raúl Guzmán',
        campus: 'Campus Industrial',
        specialty: 'Gestión de Tecnologías de Información',
        specialtyShortName: 'GTI',
        modality: 'Virtual',
        grade: 'Sexto Semestre',
        group: 'F',
        generation: '2021-08-05 / 2022-07-20',
        students: 20,
      },
      {
        id: 15,
        tutor: 'Luisa Vázquez',
        campus: 'Campus Centro',
        specialty: 'Biomedicina Informática',
        specialtyShortName: 'BIM',
        modality: 'Híbrido',
        grade: 'Séptimo Semestre',
        group: 'C',
        generation: '2021-01-25 / 2021-12-15',
        students: 23,
      },
    ];
  }
}
