import { Injectable } from '@angular/core';
import { Student } from '../models/student.model';

@Injectable({
  providedIn: 'root',
})
export class StudentsTestService {
  getData(): Student[] {
    return [
      {
        studentId: 1,
        studentCode: 'A20215678',
        name: 'Carlos',
        firstSurname: 'Hernández',
        secondSurname: 'López',
        phoneNumber: '5551234567',
        email: 'carlos.hernandez@estudiante.edu.mx',
        predictionResult: 78.25,
      },
      {
        studentId: 2,
        studentCode: 'A20218901',
        name: 'María',
        firstSurname: 'González',
        secondSurname: 'Ramírez',
        phoneNumber: '5552345678',
        email: 'maria.gonzalez@estudiante.edu.mx',
        predictionResult: null,
      },
      {
        studentId: 3,
        studentCode: 'A20219012',
        name: 'Juan',
        firstSurname: 'Rodríguez',
        secondSurname: 'Torres',
        phoneNumber: '5553456789',
        email: 'juan.rodriguez@estudiante.edu.mx',
        predictionResult: 65.75,
      },
      {
        studentId: 4,
        studentCode: 'A20210123',
        name: 'Ana',
        firstSurname: 'Martínez',
        secondSurname: 'Flores',
        phoneNumber: '5554567890',
        email: 'ana.martinez@estudiante.edu.mx',
        predictionResult: 87.3,
      },
      {
        studentId: 5,
        studentCode: 'A20211234',
        name: 'Roberto',
        firstSurname: 'López',
        secondSurname: 'García',
        phoneNumber: '5555678901',
        email: 'roberto.lopez@estudiante.edu.mx',
        predictionResult: 45.6,
      },
      {
        studentId: 6,
        studentCode: 'A20212345',
        name: 'Patricia',
        firstSurname: 'Sánchez',
        secondSurname: 'Mendoza',
        phoneNumber: '5556789012',
        email: 'patricia.sanchez@estudiante.edu.mx',
        predictionResult: 91.2,
      },
      {
        studentId: 7,
        studentCode: 'A20213456',
        name: 'Miguel',
        firstSurname: 'Pérez',
        secondSurname: 'Rivera',
        phoneNumber: '5557890123',
        email: 'miguel.perez@estudiante.edu.mx',
        predictionResult: 72.8,
      },
      {
        studentId: 8,
        studentCode: 'A20214567',
        name: 'Sofía',
        firstSurname: 'Gómez',
        secondSurname: 'Castillo',
        phoneNumber: '5558901234',
        email: 'sofia.gomez@estudiante.edu.mx',
        predictionResult: 88.9,
      },
      {
        studentId: 9,
        studentCode: 'A20216789',
        name: 'Daniel',
        firstSurname: 'Torres',
        secondSurname: 'Jiménez',
        phoneNumber: '5559012345',
        email: 'daniel.torres@estudiante.edu.mx',
        predictionResult: 67.4,
      },
      {
        studentId: 10,
        studentCode: 'A20217890',
        name: 'Alejandra',
        firstSurname: 'Díaz',
        secondSurname: 'Morales',
        phoneNumber: '5550123456',
        email: 'alejandra.diaz@estudiante.edu.mx',
        predictionResult: 95.1,
      },
      {
        studentId: 11,
        studentCode: 'A20220123',
        name: 'Fernando',
        firstSurname: 'Vargas',
        secondSurname: 'Ortega',
        phoneNumber: '5551234568',
        email: 'fernando.vargas@estudiante.edu.mx',
        predictionResult: 76.7,
      },
      {
        studentId: 12,
        studentCode: 'A20221234',
        name: 'Laura',
        firstSurname: 'Ramírez',
        secondSurname: 'Rojas',
        phoneNumber: '5552345679',
        email: 'laura.ramirez@estudiante.edu.mx',
        predictionResult: 58.25,
      },
      {
        studentId: 13,
        studentCode: 'A20222345',
        name: 'Javier',
        firstSurname: 'Cruz',
        secondSurname: 'Herrera',
        phoneNumber: '5553456790',
        email: 'javier.cruz@estudiante.edu.mx',
        predictionResult: 83.6,
      },
      {
        studentId: 14,
        studentCode: 'A20223456',
        name: 'Gabriela',
        firstSurname: 'Reyes',
        secondSurname: 'Vega',
        phoneNumber: '5554567891',
        email: 'gabriela.reyes@estudiante.edu.mx',
        predictionResult: 79.4,
      },
      {
        studentId: 15,
        studentCode: 'A20224567',
        name: 'Ricardo',
        firstSurname: 'Mendoza',
        secondSurname: 'Silva',
        phoneNumber: '5555678902',
        email: 'ricardo.mendoza@estudiante.edu.mx',
        predictionResult: 50.3,
      },
      {
        studentId: 16,
        studentCode: 'A20225678',
        name: 'Carmen',
        firstSurname: 'Flores',
        secondSurname: 'Gutiérrez',
        phoneNumber: '5556789013',
        email: 'carmen.flores@estudiante.edu.mx',
        predictionResult: 94.75,
      },
      {
        studentId: 17,
        studentCode: 'A20226789',
        name: 'Eduardo',
        firstSurname: 'Castillo',
        secondSurname: 'Soto',
        phoneNumber: '5557890124',
        email: 'eduardo.castillo@estudiante.edu.mx',
        predictionResult: 69.8,
      },
      {
        studentId: 18,
        studentCode: 'A20227890',
        name: 'Verónica',
        firstSurname: 'Santos',
        secondSurname: 'Ríos',
        phoneNumber: '5558901235',
        email: 'veronica.santos@estudiante.edu.mx',
        predictionResult: 82.15,
      },
      {
        studentId: 19,
        studentCode: 'A20228901',
        name: 'Francisco',
        firstSurname: 'Morales',
        secondSurname: 'Medina',
        phoneNumber: '5559012346',
        email: 'francisco.morales@estudiante.edu.mx',
        predictionResult: 61.9,
      },
      {
        studentId: 20,
        studentCode: 'A20229012',
        name: 'Isabel',
        firstSurname: 'Rivera',
        secondSurname: 'Luna',
        phoneNumber: '5550123457',
        email: 'isabel.rivera@estudiante.edu.mx',
        predictionResult: 89.45,
      },
    ];
  }
}
