import { Injectable } from '@angular/core';
import { User } from '../models/user.model';

@Injectable({
  providedIn: 'root',
})
export class UsersTestService {
  getData(): User[] {
    return [
      {
        userId: 1,
        email: 'carlos.gomez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Carlos',
        firstSurname: 'Gomez',
        secondSurname: 'Martinez',
        employeeCode: 'TUT1234ABCDE',
        password: 'Pass1234$',
        createdAt: '2024-05-15T08:30:22',
        isActive: true,
      },
      {
        userId: 2,
        email: 'maria.lopez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Maria',
        firstSurname: 'Lopez',
        secondSurname: 'Fernandez',
        employeeCode: 'TUT5678FGHIJ',
        password: 'Secure456!',
        createdAt: '2024-06-02T14:15:45',
        isActive: true,
      },
      {
        userId: 3,
        email: 'juan.perez@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Juan',
        firstSurname: 'Perez',
        secondSurname: 'Gonzalez',
        studentCode: 'EST2023ABC456',
        password: 'Student789#',
        createdAt: '2024-03-10T09:45:30',
        isActive: true,
      },
      {
        userId: 4,
        email: 'ana.ruiz@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Ana',
        firstSurname: 'Ruiz',
        secondSurname: 'Morales',
        studentCode: 'EST2023DEF789',
        password: 'Ana2024!',
        createdAt: '2024-03-12T11:20:15',
        isActive: true,
      },
      {
        userId: 5,
        email: 'roberto.sanchez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Roberto',
        firstSurname: 'Sanchez',
        secondSurname: 'Navarro',
        employeeCode: 'TUT9012KLMNO',
        password: 'Tutor2024%',
        createdAt: '2024-06-15T10:05:33',
        isActive: true,
      },
      {
        userId: 6,
        email: 'carmen.rodriguez@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Carmen',
        firstSurname: 'Rodriguez',
        secondSurname: 'Vega',
        studentCode: 'EST2023GHI123',
        password: 'Carmen789&',
        createdAt: '2024-04-05T13:25:40',
        isActive: true,
      },
      {
        userId: 7,
        email: 'miguel.torres@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Miguel',
        firstSurname: 'Torres',
        secondSurname: 'Jimenez',
        employeeCode: 'TUT3456PQRST',
        password: 'Miguel123$',
        createdAt: '2024-05-28T16:40:12',
        isActive: true,
      },
      {
        userId: 8,
        email: 'laura.garcia@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Laura',
        firstSurname: 'Garcia',
        secondSurname: 'Romero',
        studentCode: 'EST2023JKL456',
        password: 'Laura456#',
        createdAt: '2024-03-18T14:50:22',
        isActive: true,
      },
      {
        userId: 9,
        email: 'pedro.diaz@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Pedro',
        firstSurname: 'Diaz',
        secondSurname: 'Vargas',
        employeeCode: 'TUT7890UVWXY',
        password: 'Pedro789!',
        createdAt: '2024-06-10T09:15:30',
        isActive: true,
      },
      {
        userId: 10,
        email: 'sofia.alvarez@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Sofia',
        firstSurname: 'Alvarez',
        secondSurname: 'Rojas',
        studentCode: 'EST2023MNO789',
        password: 'Sofia2024%',
        createdAt: '2024-04-20T10:35:18',
        isActive: true,
      },
      {
        userId: 11,
        email: 'javier.hernandez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Javier',
        firstSurname: 'Hernandez',
        secondSurname: 'Castro',
        employeeCode: 'TUT2345ZABCD',
        password: 'Javier456&',
        createdAt: '2024-05-05T11:20:45',
        isActive: true,
      },
      {
        userId: 12,
        email: 'elena.moreno@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Elena',
        firstSurname: 'Moreno',
        secondSurname: 'Flores',
        studentCode: 'EST2023PQR123',
        password: 'Elena123#',
        createdAt: '2024-03-25T15:40:33',
        isActive: true,
      },
      {
        userId: 13,
        email: 'david.ramos@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'David',
        firstSurname: 'Ramos',
        secondSurname: 'Mendoza',
        employeeCode: 'TUT6789EFGHI',
        password: 'David789$',
        createdAt: '2024-06-18T13:10:20',
        isActive: true,
      },
      {
        userId: 14,
        email: 'patricia.vazquez@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Patricia',
        firstSurname: 'Vazquez',
        secondSurname: 'Aguilar',
        studentCode: 'EST2023STU456',
        password: 'Patri456!',
        createdAt: '2024-04-02T08:55:42',
        isActive: false,
      },
      {
        userId: 15,
        email: 'alejandro.reyes@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Alejandro',
        firstSurname: 'Reyes',
        secondSurname: 'Ortega',
        employeeCode: 'TUT0123JKLMN',
        password: 'Alej2024%',
        createdAt: '2024-05-12T10:30:15',
        isActive: true,
      },
      {
        userId: 16,
        email: 'monica.gutierrez@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Monica',
        firstSurname: 'Gutierrez',
        secondSurname: 'Campos',
        studentCode: 'EST2023VWX789',
        password: 'Moni789&',
        createdAt: '2024-03-30T12:25:38',
        isActive: true,
      },
      {
        userId: 17,
        email: 'raul.castillo@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Raul',
        firstSurname: 'Castillo',
        secondSurname: 'Duran',
        employeeCode: 'TUT4567OPQRS',
        password: 'Raul123#',
        createdAt: '2024-06-25T14:45:50',
        isActive: true,
      },
      {
        userId: 18,
        email: 'lucia.santos@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Lucia',
        firstSurname: 'Santos',
        secondSurname: 'Delgado',
        studentCode: 'EST2023YZA123',
        password: 'Lucia456$',
        createdAt: '2024-04-15T09:35:27',
        isActive: true,
      },
      {
        userId: 19,
        email: 'sergio.ortiz@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Sergio',
        firstSurname: 'Ortiz',
        secondSurname: 'Fuentes',
        employeeCode: 'TUT8901TUVWX',
        password: 'Sergio789!',
        createdAt: '2024-05-20T15:15:40',
        isActive: true,
      },
      {
        userId: 20,
        email: 'daniela.miranda@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Daniela',
        firstSurname: 'Miranda',
        secondSurname: 'Espinoza',
        studentCode: 'EST2023BCD456',
        password: 'Dani2024%',
        createdAt: '2024-03-05T16:50:33',
        isActive: true,
      },
      {
        userId: 21,
        email: 'alberto.cruz@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Alberto',
        firstSurname: 'Cruz',
        secondSurname: 'Herrera',
        employeeCode: 'TUT3456YABCDE',
        password: 'Alberto456&',
        createdAt: '2024-06-30T08:40:15',
        isActive: true,
      },
      {
        userId: 22,
        email: 'veronica.mendez@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Veronica',
        firstSurname: 'Mendez',
        secondSurname: 'Rios',
        studentCode: 'EST2023EFG789',
        password: 'Vero123#',
        createdAt: '2024-04-28T11:30:25',
        isActive: true,
      },
      {
        userId: 23,
        email: 'francisco.nunez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Francisco',
        firstSurname: 'Nunez',
        secondSurname: 'Acosta',
        employeeCode: 'TUT7890FGHIJ',
        password: 'Franc789$',
        createdAt: '2024-05-08T13:20:48',
        isActive: false,
      },
      {
        userId: 24,
        email: 'isabela.silva@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Isabela',
        firstSurname: 'Silva',
        secondSurname: 'Medina',
        studentCode: 'EST2023HIJ123',
        password: 'Isa456!',
        createdAt: '2024-03-15T14:10:35',
        isActive: true,
      },
      {
        userId: 25,
        email: 'gabriel.flores@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Gabriel',
        firstSurname: 'Flores',
        secondSurname: 'Cordero',
        employeeCode: 'TUT1234KLMNO',
        password: 'Gabi2024%',
        createdAt: '2024-06-05T10:50:22',
        isActive: true,
      },
      {
        userId: 26,
        email: 'adriana.rojas@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Adriana',
        firstSurname: 'Rojas',
        secondSurname: 'Paredes',
        studentCode: 'EST2023KLM456',
        password: 'Adri789&',
        createdAt: '2024-04-10T09:25:18',
        isActive: true,
      },
      {
        userId: 27,
        email: 'hector.vargas@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Hector',
        firstSurname: 'Vargas',
        secondSurname: 'Salazar',
        employeeCode: 'TUT5678PQRST',
        password: 'Hector123#',
        createdAt: '2024-05-25T15:40:30',
        isActive: true,
      },
      {
        userId: 28,
        email: 'claudia.molina@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Claudia',
        firstSurname: 'Molina',
        secondSurname: 'Vidal',
        studentCode: 'EST2023NOP789',
        password: 'Clau456$',
        createdAt: '2024-03-20T12:15:45',
        isActive: true,
      },
      {
        userId: 29,
        email: 'jorge.guzman@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Jorge',
        firstSurname: 'Guzman',
        secondSurname: 'Cabrera',
        employeeCode: 'TUT9012UVWXY',
        password: 'Jorge789!',
        createdAt: '2024-06-12T13:35:18',
        isActive: true,
      },
      {
        userId: 30,
        email: 'alicia.estrada@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Alicia',
        firstSurname: 'Estrada',
        secondSurname: 'Soto',
        studentCode: 'EST2023QRS123',
        password: 'Ali2024%',
        createdAt: '2024-04-25T10:45:33',
        isActive: true,
      },
      {
        userId: 31,
        email: 'ernesto.cano@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Ernesto',
        firstSurname: 'Cano',
        secondSurname: 'Ponce',
        employeeCode: 'TUT2345ZABCD',
        password: 'Ernesto456&',
        createdAt: '2024-05-18T14:30:40',
        isActive: true,
      },
      {
        userId: 32,
        email: 'natalia.palacios@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Natalia',
        firstSurname: 'Palacios',
        secondSurname: 'Montes',
        studentCode: 'EST2023TUV456',
        password: 'Nati123#',
        createdAt: '2024-03-28T15:20:15',
        isActive: true,
      },
      {
        userId: 33,
        email: 'oscar.aguirre@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Oscar',
        firstSurname: 'Aguirre',
        secondSurname: 'Ochoa',
        employeeCode: 'TUT6789EFGHI',
        password: 'Oscar789$',
        createdAt: '2024-06-22T09:55:27',
        isActive: true,
      },
      {
        userId: 34,
        email: 'beatriz.cortes@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Beatriz',
        firstSurname: 'Cortes',
        secondSurname: 'Valle',
        studentCode: 'EST2023WXY789',
        password: 'Bea456!',
        createdAt: '2024-04-05T08:40:33',
        isActive: true,
      },
      {
        userId: 35,
        email: 'manuel.villegas@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Manuel',
        firstSurname: 'Villegas',
        secondSurname: 'Arce',
        employeeCode: 'TUT0123JKLMN',
        password: 'Manu2024%',
        createdAt: '2024-05-30T11:15:48',
        isActive: false,
      },
      {
        userId: 36,
        email: 'diana.rivas@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Diana',
        firstSurname: 'Rivas',
        secondSurname: 'Salgado',
        studentCode: 'EST2023ZAB123',
        password: 'Diana789&',
        createdAt: '2024-03-22T12:50:22',
        isActive: true,
      },
      {
        userId: 37,
        email: 'julio.carrillo@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Julio',
        firstSurname: 'Carrillo',
        secondSurname: 'Pineda',
        employeeCode: 'TUT4567OPQRS',
        password: 'Julio123#',
        createdAt: '2024-06-08T13:25:40',
        isActive: true,
      },
      {
        userId: 38,
        email: 'valeria.escobar@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Valeria',
        firstSurname: 'Escobar',
        secondSurname: 'Rosales',
        studentCode: 'EST2023CDE456',
        password: 'Vale456$',
        createdAt: '2024-04-18T14:35:15',
        isActive: true,
      },
      {
        userId: 39,
        email: 'ramon.calderon@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Ramon',
        firstSurname: 'Calderon',
        secondSurname: 'Morales',
        employeeCode: 'TUT8901TUVWX',
        password: 'Ramon789!',
        createdAt: '2024-05-15T15:50:33',
        isActive: true,
      },
      {
        userId: 40,
        email: 'cristina.pacheco@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Cristina',
        firstSurname: 'Pacheco',
        secondSurname: 'Huerta',
        studentCode: 'EST2023FGH789',
        password: 'Cris2024%',
        createdAt: '2024-03-08T16:20:48',
        isActive: true,
      },
      {
        userId: 41,
        email: 'martin.solis@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Martin',
        firstSurname: 'Solis',
        secondSurname: 'Luna',
        employeeCode: 'TUT3456YABCDE',
        password: 'Martin456&',
        createdAt: '2024-06-28T09:40:22',
        isActive: true,
      },
      {
        userId: 42,
        email: 'lorena.pineda@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Lorena',
        firstSurname: 'Pineda',
        secondSurname: 'Andrade',
        studentCode: 'EST2023IJK123',
        password: 'Lore123#',
        createdAt: '2024-04-22T10:30:15',
        isActive: true,
      },
      {
        userId: 43,
        email: 'rafael.benitez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Rafael',
        firstSurname: 'Benitez',
        secondSurname: 'Galvan',
        employeeCode: 'TUT7890FGHIJ',
        password: 'Rafa789$',
        createdAt: '2024-05-05T12:15:40',
        isActive: true,
      },
      {
        userId: 44,
        email: 'susana.rangel@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Susana',
        firstSurname: 'Rangel',
        secondSurname: 'Mejia',
        studentCode: 'EST2023LMN456',
        password: 'Susi456!',
        createdAt: '2024-03-17T13:55:33',
        isActive: true,
      },
      {
        userId: 45,
        email: 'fernando.avila@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Fernando',
        firstSurname: 'Avila',
        secondSurname: 'Gallegos',
        employeeCode: 'TUT1234KLMNO',
        password: 'Fer2024%',
        createdAt: '2024-06-15T14:40:18',
        isActive: true,
      },
      {
        userId: 46,
        email: 'martha.arellano@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Martha',
        firstSurname: 'Arellano',
        secondSurname: 'Zamora',
        studentCode: 'EST2023OPQ789',
        password: 'Martha789&',
        createdAt: '2024-04-30T15:20:45',
        isActive: false,
      },
      {
        userId: 47,
        email: 'arturo.montes@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Arturo',
        firstSurname: 'Montes',
        secondSurname: 'Cervantes',
        employeeCode: 'TUT5678PQRST',
        password: 'Arturo123#',
        createdAt: '2024-05-22T16:10:33',
        isActive: true,
      },
      {
        userId: 48,
        email: 'raquel.leon@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Raquel',
        firstSurname: 'Leon',
        secondSurname: 'Valencia',
        studentCode: 'EST2023RST123',
        password: 'Raquel456$',
        createdAt: '2024-03-25T09:45:27',
        isActive: true,
      },
      {
        userId: 49,
        email: 'simon.lugo@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Simon',
        firstSurname: 'Lugo',
        secondSurname: 'Alvarado',
        employeeCode: 'TUT9012UVWXY',
        password: 'Simon789!',
        createdAt: '2024-06-20T10:35:48',
        isActive: true,
      },
      {
        userId: 50,
        email: 'olivia.miranda@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Olivia',
        firstSurname: 'Miranda',
        secondSurname: 'Guevara',
        studentCode: 'EST2023UVW456',
        password: 'Oli2024%',
        createdAt: '2024-04-12T11:50:22',
        isActive: true,
      },
      {
        userId: 51,
        email: 'carlos.martinez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Carlos',
        firstSurname: 'Martinez',
        secondSurname: 'Flores',
        employeeCode: 'TUT5432MNOPQ',
        password: 'CarlosM24$',
        createdAt: '2024-07-01T08:15:22',
        isActive: true,
      },
      {
        userId: 52,
        email: 'maria.fernandez@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Maria',
        firstSurname: 'Fernandez',
        secondSurname: 'Gutierrez',
        studentCode: 'EST2023XYZ789',
        password: 'Maria456#',
        createdAt: '2024-03-05T09:30:45',
        isActive: true,
      },
      {
        userId: 53,
        email: 'juan.gonzalez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Juan',
        firstSurname: 'Gonzalez',
        secondSurname: 'Herrera',
        employeeCode: 'TUT8765RSTUV',
        password: 'Juan2024%',
        createdAt: '2024-06-10T10:45:30',
        isActive: true,
      },
      {
        userId: 54,
        email: 'ana.morales@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Ana',
        firstSurname: 'Morales',
        secondSurname: 'Castillo',
        studentCode: 'EST2023DEF123',
        password: 'Ana789&',
        createdAt: '2024-04-15T11:20:15',
        isActive: true,
      },
      {
        userId: 55,
        email: 'roberto.navarro@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Roberto',
        firstSurname: 'Navarro',
        secondSurname: 'Mendoza',
        employeeCode: 'TUT1098WXYZA',
        password: 'Rob123#',
        createdAt: '2024-07-05T12:35:33',
        isActive: true,
      },
      {
        userId: 56,
        email: 'carmen.vega@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Carmen',
        firstSurname: 'Vega',
        secondSurname: 'Sanchez',
        studentCode: 'EST2023GHI456',
        password: 'Carm456$',
        createdAt: '2024-03-20T13:40:40',
        isActive: true,
      },
      {
        userId: 57,
        email: 'miguel.jimenez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Miguel',
        firstSurname: 'Jimenez',
        secondSurname: 'Torres',
        employeeCode: 'TUT4321BCDEF',
        password: 'Mig2024%',
        createdAt: '2024-06-25T14:50:22',
        isActive: true,
      },
      {
        userId: 58,
        email: 'laura.romero@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Laura',
        firstSurname: 'Romero',
        secondSurname: 'Garcia',
        studentCode: 'EST2023JKL789',
        password: 'Laura789!',
        createdAt: '2024-04-30T15:15:18',
        isActive: false,
      },
      {
        userId: 59,
        email: 'pedro.vargas@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Pedro',
        firstSurname: 'Vargas',
        secondSurname: 'Diaz',
        employeeCode: 'TUT7654GHIJK',
        password: 'Pedro123&',
        createdAt: '2024-07-10T08:30:45',
        isActive: true,
      },
      {
        userId: 60,
        email: 'sofia.rojas@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Sofia',
        firstSurname: 'Rojas',
        secondSurname: 'Alvarez',
        studentCode: 'EST2023MNO123',
        password: 'Sof456#',
        createdAt: '2024-03-15T09:45:33',
        isActive: true,
      },
      {
        userId: 61,
        email: 'javier.castro@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Javier',
        firstSurname: 'Castro',
        secondSurname: 'Hernandez',
        employeeCode: 'TUT0987LMNOP',
        password: 'Jav2024$',
        createdAt: '2024-06-20T10:50:20',
        isActive: true,
      },
      {
        userId: 62,
        email: 'elena.flores@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Elena',
        firstSurname: 'Flores',
        secondSurname: 'Moreno',
        studentCode: 'EST2023PQR456',
        password: 'Elena789%',
        createdAt: '2024-04-05T11:25:48',
        isActive: true,
      },
      {
        userId: 63,
        email: 'david.mendoza@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'David',
        firstSurname: 'Mendoza',
        secondSurname: 'Ramos',
        employeeCode: 'TUT3210QRSTU',
        password: 'David123!',
        createdAt: '2024-07-15T12:40:15',
        isActive: true,
      },
      {
        userId: 64,
        email: 'patricia.aguilar@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Patricia',
        firstSurname: 'Aguilar',
        secondSurname: 'Vazquez',
        studentCode: 'EST2023STU789',
        password: 'Pat456&',
        createdAt: '2024-03-25T13:15:33',
        isActive: true,
      },
      {
        userId: 65,
        email: 'alejandro.ortega@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Alejandro',
        firstSurname: 'Ortega',
        secondSurname: 'Reyes',
        employeeCode: 'TUT6543VWXYZ',
        password: 'Ale2024#',
        createdAt: '2024-06-30T14:30:40',
        isActive: true,
      },
      {
        userId: 66,
        email: 'monica.campos@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Monica',
        firstSurname: 'Campos',
        secondSurname: 'Gutierrez',
        studentCode: 'EST2023VWX123',
        password: 'Monica789$',
        createdAt: '2024-04-10T15:45:22',
        isActive: true,
      },
      {
        userId: 67,
        email: 'raul.duran@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Raul',
        firstSurname: 'Duran',
        secondSurname: 'Castillo',
        employeeCode: 'TUT2109ABCDE',
        password: 'Raul456%',
        createdAt: '2024-07-20T08:20:48',
        isActive: false,
      },
      {
        userId: 68,
        email: 'lucia.delgado@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Lucia',
        firstSurname: 'Delgado',
        secondSurname: 'Santos',
        studentCode: 'EST2023YZA456',
        password: 'Lucia123!',
        createdAt: '2024-03-30T09:35:15',
        isActive: true,
      },
      {
        userId: 69,
        email: 'sergio.fuentes@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Sergio',
        firstSurname: 'Fuentes',
        secondSurname: 'Ortiz',
        employeeCode: 'TUT5432FGHIJ',
        password: 'Ser2024&',
        createdAt: '2024-06-15T10:50:33',
        isActive: true,
      },
      {
        userId: 70,
        email: 'daniela.espinoza@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Daniela',
        firstSurname: 'Espinoza',
        secondSurname: 'Miranda',
        studentCode: 'EST2023BCD789',
        password: 'Dani456#',
        createdAt: '2024-04-20T11:40:20',
        isActive: true,
      },
      {
        userId: 71,
        email: 'alberto.herrera@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Alberto',
        firstSurname: 'Herrera',
        secondSurname: 'Cruz',
        employeeCode: 'TUT8765KLMNO',
        password: 'Alberto123$',
        createdAt: '2024-07-25T12:15:48',
        isActive: true,
      },
      {
        userId: 72,
        email: 'veronica.rios@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Veronica',
        firstSurname: 'Rios',
        secondSurname: 'Mendez',
        studentCode: 'EST2023EFG123',
        password: 'Vero456%',
        createdAt: '2024-03-10T13:30:22',
        isActive: true,
      },
      {
        userId: 73,
        email: 'francisco.acosta@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Francisco',
        firstSurname: 'Acosta',
        secondSurname: 'Nunez',
        employeeCode: 'TUT1098PQRST',
        password: 'Fran2024!',
        createdAt: '2024-06-05T14:45:15',
        isActive: true,
      },
      {
        userId: 74,
        email: 'isabela.medina@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Isabela',
        firstSurname: 'Medina',
        secondSurname: 'Silva',
        studentCode: 'EST2023HIJ456',
        password: 'Isa123&',
        createdAt: '2024-04-25T15:20:40',
        isActive: true,
      },
      {
        userId: 75,
        email: 'gabriel.cordero@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Gabriel',
        firstSurname: 'Cordero',
        secondSurname: 'Flores',
        employeeCode: 'TUT4321UVWXY',
        password: 'Gab456$',
        createdAt: '2024-07-30T08:35:33',
        isActive: true,
      },
      {
        userId: 76,
        email: 'adriana.paredes@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Adriana',
        firstSurname: 'Paredes',
        secondSurname: 'Rojas',
        studentCode: 'EST2023KLM789',
        password: 'Adri123#',
        createdAt: '2024-03-15T09:50:18',
        isActive: false,
      },
      {
        userId: 77,
        email: 'hector.salazar@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Hector',
        firstSurname: 'Salazar',
        secondSurname: 'Vargas',
        employeeCode: 'TUT7654ZABCD',
        password: 'Hec2024%',
        createdAt: '2024-06-10T10:15:45',
        isActive: true,
      },
      {
        userId: 78,
        email: 'claudia.vidal@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Claudia',
        firstSurname: 'Vidal',
        secondSurname: 'Molina',
        studentCode: 'EST2023NOP123',
        password: 'Clau456!',
        createdAt: '2024-05-05T11:30:30',
        isActive: true,
      },
      {
        userId: 79,
        email: 'jorge.cabrera@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Jorge',
        firstSurname: 'Cabrera',
        secondSurname: 'Guzman',
        employeeCode: 'TUT0987EFGHI',
        password: 'Jorge123&',
        createdAt: '2024-08-01T12:45:22',
        isActive: true,
      },
      {
        userId: 80,
        email: 'alicia.soto@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Alicia',
        firstSurname: 'Soto',
        secondSurname: 'Estrada',
        studentCode: 'EST2023QRS456',
        password: 'Ali456$',
        createdAt: '2024-03-20T13:15:48',
        isActive: true,
      },
      {
        userId: 81,
        email: 'ernesto.ponce@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Ernesto',
        firstSurname: 'Ponce',
        secondSurname: 'Cano',
        employeeCode: 'TUT3210JKLMN',
        password: 'Ern2024#',
        createdAt: '2024-06-25T14:30:15',
        isActive: true,
      },
      {
        userId: 82,
        email: 'natalia.montes@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Natalia',
        firstSurname: 'Montes',
        secondSurname: 'Palacios',
        studentCode: 'EST2023TUV789',
        password: 'Nat123%',
        createdAt: '2024-05-10T15:45:33',
        isActive: true,
      },
      {
        userId: 83,
        email: 'oscar.ochoa@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Oscar',
        firstSurname: 'Ochoa',
        secondSurname: 'Aguirre',
        employeeCode: 'TUT6543OPQRS',
        password: 'Oscar456!',
        createdAt: '2024-08-05T08:20:40',
        isActive: true,
      },
      {
        userId: 84,
        email: 'beatriz.valle@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Beatriz',
        firstSurname: 'Valle',
        secondSurname: 'Cortes',
        studentCode: 'EST2023WXY123',
        password: 'Bea123&',
        createdAt: '2024-03-25T09:35:22',
        isActive: true,
      },
      {
        userId: 85,
        email: 'manuel.arce@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Manuel',
        firstSurname: 'Arce',
        secondSurname: 'Villegas',
        employeeCode: 'TUT2109TUVWX',
        password: 'Man2024$',
        createdAt: '2024-06-30T10:50:48',
        isActive: true,
      },
      {
        userId: 86,
        email: 'diana.salgado@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Diana',
        firstSurname: 'Salgado',
        secondSurname: 'Rivas',
        studentCode: 'EST2023ZAB456',
        password: 'Diana456#',
        createdAt: '2024-05-15T11:15:15',
        isActive: true,
      },
      {
        userId: 87,
        email: 'julio.pineda@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Julio',
        firstSurname: 'Pineda',
        secondSurname: 'Carrillo',
        employeeCode: 'TUT5432YABCDEF',
        password: 'Julio789$',
        createdAt: '2024-08-10T12:30:33',
        isActive: false,
      },
      {
        userId: 88,
        email: 'valeria.rosales@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Valeria',
        firstSurname: 'Rosales',
        secondSurname: 'Escobar',
        studentCode: 'EST2023CDE789',
        password: 'Val123%',
        createdAt: '2024-03-30T13:45:20',
        isActive: true,
      },
      {
        userId: 89,
        email: 'ramon.morales@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Ramon',
        firstSurname: 'Morales',
        secondSurname: 'Calderon',
        employeeCode: 'TUT8765GHIJKL',
        password: 'Ram2024!',
        createdAt: '2024-07-05T14:20:45',
        isActive: true,
      },
      {
        userId: 90,
        email: 'cristina.huerta@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Cristina',
        firstSurname: 'Huerta',
        secondSurname: 'Pacheco',
        studentCode: 'EST2023FGH123',
        password: 'Cris456&',
        createdAt: '2024-05-20T15:35:18',
        isActive: true,
      },
      {
        userId: 91,
        email: 'martin.luna@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Martin',
        firstSurname: 'Luna',
        secondSurname: 'Solis',
        employeeCode: 'TUT1098MNOPQR',
        password: 'Mart123#',
        createdAt: '2024-08-15T08:50:33',
        isActive: true,
      },
      {
        userId: 92,
        email: 'lorena.andrade@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Lorena',
        firstSurname: 'Andrade',
        secondSurname: 'Pineda',
        studentCode: 'EST2023IJK456',
        password: 'Lore456$',
        createdAt: '2024-03-05T09:15:48',
        isActive: true,
      },
      {
        userId: 93,
        email: 'rafael.galvan@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Rafael',
        firstSurname: 'Galvan',
        secondSurname: 'Benitez',
        employeeCode: 'TUT4321STUVW',
        password: 'Rafa2024%',
        createdAt: '2024-07-10T10:30:22',
        isActive: true,
      },
      {
        userId: 94,
        email: 'susana.mejia@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Susana',
        firstSurname: 'Mejia',
        secondSurname: 'Rangel',
        studentCode: 'EST2023LMN789',
        password: 'Sus123!',
        createdAt: '2024-05-25T11:45:15',
        isActive: true,
      },
      {
        userId: 95,
        email: 'fernando.gallegos@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Fernando',
        firstSurname: 'Gallegos',
        secondSurname: 'Avila',
        employeeCode: 'TUT7654XYZABC',
        password: 'Fer456&',
        createdAt: '2024-08-20T12:20:40',
        isActive: true,
      },
      {
        userId: 96,
        email: 'martha.zamora@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Martha',
        firstSurname: 'Zamora',
        secondSurname: 'Arellano',
        studentCode: 'EST2023OPQ123',
        password: 'Martha123#',
        createdAt: '2024-03-10T13:35:33',
        isActive: true,
      },
      {
        userId: 97,
        email: 'arturo.cervantes@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Arturo',
        firstSurname: 'Cervantes',
        secondSurname: 'Montes',
        employeeCode: 'TUT0987DEFGHI',
        password: 'Art2024$',
        createdAt: '2024-07-15T14:50:18',
        isActive: true,
      },
      {
        userId: 98,
        email: 'raquel.valencia@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Raquel',
        firstSurname: 'Valencia',
        secondSurname: 'Leon',
        studentCode: 'EST2023RST456',
        password: 'Raq456%',
        createdAt: '2024-05-30T15:15:45',
        isActive: false,
      },
      {
        userId: 99,
        email: 'simon.alvarado@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Simon',
        firstSurname: 'Alvarado',
        secondSurname: 'Lugo',
        employeeCode: 'TUT3210JKLMNO',
        password: 'Simon123!',
        createdAt: '2024-08-25T08:30:33',
        isActive: true,
      },
      {
        userId: 100,
        email: 'olivia.guevara@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Olivia',
        firstSurname: 'Guevara',
        secondSurname: 'Miranda',
        studentCode: 'EST2023UVW789',
        password: 'Oli123&',
        createdAt: '2024-03-15T09:45:20',
        isActive: true,
      },
      {
        userId: 101,
        email: 'carlos.lopez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Carlos',
        firstSurname: 'Lopez',
        secondSurname: 'Ramirez',
        employeeCode: 'TUT6543PQRSTU',
        password: 'CarlosL24#',
        createdAt: '2024-07-20T10:20:48',
        isActive: true,
      },
      {
        userId: 102,
        email: 'maria.gonzalez@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Maria',
        firstSurname: 'Gonzalez',
        secondSurname: 'Torres',
        studentCode: 'EST2023XYZ123',
        password: 'MariaG56$',
        createdAt: '2024-06-05T11:35:15',
        isActive: true,
      },
      {
        userId: 103,
        email: 'juan.martinez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Juan',
        firstSurname: 'Martinez',
        secondSurname: 'Rodriguez',
        employeeCode: 'TUT2109VWXYZ',
        password: 'JuanM24%',
        createdAt: '2024-08-30T12:50:33',
        isActive: true,
      },
    ];
  }
}
