import { Injectable } from '@angular/core';
import { User } from '../models/user.model';

@Injectable({
  providedIn: 'root',
})
export class UsersTestService {
  getData(): User[] {
    return [
      {
        userId: 1,
        email: 'carlos.gomez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Carlos',
        firstSurname: 'Gomez',
        secondSurname: 'Martinez',
        key: 'TUT1234ABCDE',
        createdAt: '2025-03-10T03:25:08.083009906Z',
        isActive: true,
        phoneNumber: '1242073233',
      },
      {
        userId: 2,
        email: 'maria.lopez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Maria',
        firstSurname: 'Lopez',
        secondSurname: 'Fernandez',
        key: 'TUT5678FGHIJ',
        createdAt: '2025-03-10T02:23:02.672881Z',
        isActive: true,
        phoneNumber: '4901465796',
      },
      {
        userId: 3,
        email: 'juan.perez@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Juan',
        firstSurname: 'Perez',
        secondSurname: 'Gonzalez',
        key: 'EST2023ABC456',
        createdAt: '2025-03-10T03:19:58.067920083Z',
        isActive: true,
        phoneNumber: '2340027135',
      },
      {
        userId: 4,
        email: 'ana.ruiz@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Ana',
        firstSurname: 'Ruiz',
        secondSurname: 'Morales',
        key: 'EST2023DEF789',
        createdAt: '2025-03-10T03:20:41.470523836Z',
        isActive: true,
        phoneNumber: '9684283770',
      },
      {
        userId: 5,
        email: 'roberto.sanchez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Roberto',
        firstSurname: 'Sanchez',
        secondSurname: 'Navarro',
        key: 'TUT9012KLMNO',
        createdAt: '2024-06-15T10:05:33',
        isActive: true,
        phoneNumber: '7094871880',
      },
      {
        userId: 6,
        email: 'carmen.rodriguez@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Carmen',
        firstSurname: 'Rodriguez',
        secondSurname: 'Vega',
        key: 'EST2023GHI123',
        createdAt: '2024-04-05T13:25:40',
        isActive: true,
        phoneNumber: '1550572563',
      },
      {
        userId: 7,
        email: 'miguel.torres@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Miguel',
        firstSurname: 'Torres',
        secondSurname: 'Jimenez',
        key: 'TUT3456PQRST',
        createdAt: '2024-05-28T16:40:12',
        isActive: true,
        phoneNumber: '7994579895',
      },
      {
        userId: 8,
        email: 'laura.garcia@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Laura',
        firstSurname: 'Garcia',
        secondSurname: 'Romero',
        key: 'EST2023JKL456',
        createdAt: '2024-03-18T14:50:22',
        isActive: true,
        phoneNumber: '3368777711',
      },
      {
        userId: 9,
        email: 'pedro.diaz@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Pedro',
        firstSurname: 'Diaz',
        secondSurname: 'Vargas',
        key: 'TUT7890UVWXY',
        createdAt: '2024-06-10T09:15:30',
        isActive: true,
        phoneNumber: '8028185173',
      },
      {
        userId: 10,
        email: 'sofia.alvarez@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Sofia',
        firstSurname: 'Alvarez',
        secondSurname: 'Rojas',
        key: 'EST2023MNO789',
        createdAt: '2024-04-20T10:35:18',
        isActive: true,
        phoneNumber: '1809850558',
      },
      {
        userId: 11,
        email: 'javier.hernandez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Javier',
        firstSurname: 'Hernandez',
        secondSurname: 'Castro',
        key: 'TUT2345ZABCD',
        createdAt: '2024-05-05T11:20:45',
        isActive: true,
        phoneNumber: '8519758557',
      },
      {
        userId: 12,
        email: 'elena.moreno@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Elena',
        firstSurname: 'Moreno',
        secondSurname: 'Flores',
        key: 'EST2023PQR123',
        createdAt: '2024-03-25T15:40:33',
        isActive: true,
        phoneNumber: '7651328113',
      },
      {
        userId: 13,
        email: 'david.ramos@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'David',
        firstSurname: 'Ramos',
        secondSurname: 'Mendoza',
        key: 'TUT6789EFGHI',
        createdAt: '2024-06-18T13:10:20',
        isActive: true,
        phoneNumber: '3965612930',
      },
      {
        userId: 14,
        email: 'patricia.vazquez@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Patricia',
        firstSurname: 'Vazquez',
        secondSurname: 'Aguilar',
        key: 'EST2023STU456',
        createdAt: '2024-04-02T08:55:42',
        isActive: false,
        phoneNumber: '7017444733',
      },
      {
        userId: 15,
        email: 'alejandro.reyes@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Alejandro',
        firstSurname: 'Reyes',
        secondSurname: 'Ortega',
        key: 'TUT0123JKLMN',
        createdAt: '2024-05-12T10:30:15',
        isActive: true,
        phoneNumber: '6001760605',
      },
      {
        userId: 16,
        email: 'monica.gutierrez@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Monica',
        firstSurname: 'Gutierrez',
        secondSurname: 'Campos',
        key: 'EST2023VWX789',
        createdAt: '2024-03-30T12:25:38',
        isActive: true,
        phoneNumber: '2558567984',
      },
      {
        userId: 17,
        email: 'raul.castillo@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Raul',
        firstSurname: 'Castillo',
        secondSurname: 'Duran',
        key: 'TUT4567OPQRS',
        createdAt: '2024-06-25T14:45:50',
        isActive: true,
        phoneNumber: '4584960402',
      },
      {
        userId: 18,
        email: 'lucia.santos@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Lucia',
        firstSurname: 'Santos',
        secondSurname: 'Delgado',
        key: 'EST2023YZA123',
        createdAt: '2024-04-15T09:35:27',
        isActive: true,
        phoneNumber: '1495235264',
      },
      {
        userId: 19,
        email: 'sergio.ortiz@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Sergio',
        firstSurname: 'Ortiz',
        secondSurname: 'Fuentes',
        key: 'TUT8901TUVWX',
        createdAt: '2024-05-20T15:15:40',
        isActive: true,
        phoneNumber: '7155554015',
      },
      {
        userId: 20,
        email: 'daniela.miranda@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Daniela',
        firstSurname: 'Miranda',
        secondSurname: 'Espinoza',
        key: 'EST2023BCD456',
        createdAt: '2024-03-05T16:50:33',
        isActive: true,
        phoneNumber: '3727755247',
      },
      {
        userId: 21,
        email: 'alberto.cruz@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Alberto',
        firstSurname: 'Cruz',
        secondSurname: 'Herrera',
        key: 'TUT3456YABCDE',
        createdAt: '2024-06-30T08:40:15',
        isActive: true,
        phoneNumber: '6617763759',
      },
      {
        userId: 22,
        email: 'veronica.mendez@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Veronica',
        firstSurname: 'Mendez',
        secondSurname: 'Rios',
        key: 'EST2023EFG789',
        createdAt: '2024-04-28T11:30:25',
        isActive: true,
        phoneNumber: '7081808260',
      },
      {
        userId: 23,
        email: 'francisco.nunez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Francisco',
        firstSurname: 'Nunez',
        secondSurname: 'Acosta',
        key: 'TUT7890FGHIJ',
        createdAt: '2024-05-08T13:20:48',
        isActive: false,
        phoneNumber: '3965308033',
      },
      {
        userId: 24,
        email: 'isabela.silva@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Isabela',
        firstSurname: 'Silva',
        secondSurname: 'Medina',
        key: 'EST2023HIJ123',
        createdAt: '2024-03-15T14:10:35',
        isActive: true,
        phoneNumber: '1752855352',
      },
      {
        userId: 25,
        email: 'gabriel.flores@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Gabriel',
        firstSurname: 'Flores',
        secondSurname: 'Cordero',
        key: 'TUT1234KLMNO',
        createdAt: '2024-06-05T10:50:22',
        isActive: true,
        phoneNumber: '7930868545',
      },
      {
        userId: 26,
        email: 'adriana.rojas@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Adriana',
        firstSurname: 'Rojas',
        secondSurname: 'Paredes',
        key: 'EST2023KLM456',
        createdAt: '2024-04-10T09:25:18',
        isActive: true,
        phoneNumber: '3876450123',
      },
      {
        userId: 27,
        email: 'hector.vargas@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Hector',
        firstSurname: 'Vargas',
        secondSurname: 'Salazar',
        key: 'TUT5678PQRST',
        createdAt: '2024-05-25T15:40:30',
        isActive: true,
        phoneNumber: '8224125248',
      },
      {
        userId: 28,
        email: 'claudia.molina@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Claudia',
        firstSurname: 'Molina',
        secondSurname: 'Vidal',
        key: 'EST2023NOP789',
        createdAt: '2024-03-20T12:15:45',
        isActive: true,
        phoneNumber: '3473246485',
      },
      {
        userId: 29,
        email: 'jorge.guzman@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Jorge',
        firstSurname: 'Guzman',
        secondSurname: 'Cabrera',
        key: 'TUT9012UVWXY',
        createdAt: '2024-06-12T13:35:18',
        isActive: true,
        phoneNumber: '8655459268',
      },
      {
        userId: 30,
        email: 'alicia.estrada@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Alicia',
        firstSurname: 'Estrada',
        secondSurname: 'Soto',
        key: 'EST2023QRS123',
        createdAt: '2024-04-25T10:45:33',
        isActive: true,
        phoneNumber: '5102080060',
      },
      {
        userId: 31,
        email: 'ernesto.cano@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Ernesto',
        firstSurname: 'Cano',
        secondSurname: 'Ponce',
        key: 'TUT2345ZABCD',
        createdAt: '2024-05-18T14:30:40',
        isActive: true,
        phoneNumber: '8101709639',
      },
      {
        userId: 32,
        email: 'natalia.palacios@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Natalia',
        firstSurname: 'Palacios',
        secondSurname: 'Montes',
        key: 'EST2023TUV456',
        createdAt: '2024-03-28T15:20:15',
        isActive: true,
        phoneNumber: '1850119318',
      },
      {
        userId: 33,
        email: 'oscar.aguirre@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Oscar',
        firstSurname: 'Aguirre',
        secondSurname: 'Ochoa',
        key: 'TUT6789EFGHI',
        createdAt: '2024-06-22T09:55:27',
        isActive: true,
        phoneNumber: '9985696429',
      },
      {
        userId: 34,
        email: 'beatriz.cortes@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Beatriz',
        firstSurname: 'Cortes',
        secondSurname: 'Valle',
        key: 'EST2023WXY789',
        createdAt: '2024-04-05T08:40:33',
        isActive: true,
        phoneNumber: '3874074176',
      },
      {
        userId: 35,
        email: 'manuel.villegas@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Manuel',
        firstSurname: 'Villegas',
        secondSurname: 'Arce',
        key: 'TUT0123JKLMN',
        createdAt: '2024-05-30T11:15:48',
        isActive: false,
        phoneNumber: '2545859018',
      },
      {
        userId: 36,
        email: 'diana.rivas@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Diana',
        firstSurname: 'Rivas',
        secondSurname: 'Salgado',
        key: 'EST2023ZAB123',
        createdAt: '2024-03-22T12:50:22',
        isActive: true,
        phoneNumber: '9710802831',
      },
      {
        userId: 37,
        email: 'julio.carrillo@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Julio',
        firstSurname: 'Carrillo',
        secondSurname: 'Pineda',
        key: 'TUT4567OPQRS',
        createdAt: '2024-06-08T13:25:40',
        isActive: true,
        phoneNumber: '9992720050',
      },
      {
        userId: 38,
        email: 'valeria.escobar@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Valeria',
        firstSurname: 'Escobar',
        secondSurname: 'Rosales',
        key: 'EST2023CDE456',
        createdAt: '2024-04-18T14:35:15',
        isActive: true,
        phoneNumber: '6421236819',
      },
      {
        userId: 39,
        email: 'ramon.calderon@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Ramon',
        firstSurname: 'Calderon',
        secondSurname: 'Morales',
        key: 'TUT8901TUVWX',
        createdAt: '2024-05-15T15:50:33',
        isActive: true,
        phoneNumber: '2775293307',
      },
      {
        userId: 40,
        email: 'cristina.pacheco@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Cristina',
        firstSurname: 'Pacheco',
        secondSurname: 'Huerta',
        key: 'EST2023FGH789',
        createdAt: '2024-03-08T16:20:48',
        isActive: true,
        phoneNumber: '5206611060',
      },
      {
        userId: 41,
        email: 'martin.solis@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Martin',
        firstSurname: 'Solis',
        secondSurname: 'Luna',
        key: 'TUT3456YABCDE',
        createdAt: '2024-06-28T09:40:22',
        isActive: true,
        phoneNumber: '1295355613',
      },
      {
        userId: 42,
        email: 'lorena.pineda@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Lorena',
        firstSurname: 'Pineda',
        secondSurname: 'Andrade',
        key: 'EST2023IJK123',
        createdAt: '2024-04-22T10:30:15',
        isActive: true,
        phoneNumber: '8729082310',
      },
      {
        userId: 43,
        email: 'rafael.benitez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Rafael',
        firstSurname: 'Benitez',
        secondSurname: 'Galvan',
        key: 'TUT7890FGHIJ',
        createdAt: '2024-05-05T12:15:40',
        isActive: true,
        phoneNumber: '4227807202',
      },
      {
        userId: 44,
        email: 'susana.rangel@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Susana',
        firstSurname: 'Rangel',
        secondSurname: 'Mejia',
        key: 'EST2023LMN456',
        createdAt: '2024-03-17T13:55:33',
        isActive: true,
        phoneNumber: '1600874606',
      },
      {
        userId: 45,
        email: 'fernando.avila@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Fernando',
        firstSurname: 'Avila',
        secondSurname: 'Gallegos',
        key: 'TUT1234KLMNO',
        createdAt: '2024-06-15T14:40:18',
        isActive: true,
        phoneNumber: '8861568673',
      },
      {
        userId: 46,
        email: 'martha.arellano@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Martha',
        firstSurname: 'Arellano',
        secondSurname: 'Zamora',
        key: 'EST2023OPQ789',
        createdAt: '2024-04-30T15:20:45',
        isActive: false,
        phoneNumber: '6386721703',
      },
      {
        userId: 47,
        email: 'arturo.montes@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Arturo',
        firstSurname: 'Montes',
        secondSurname: 'Cervantes',
        key: 'TUT5678PQRST',
        createdAt: '2024-05-22T16:10:33',
        isActive: true,
        phoneNumber: '9319884010',
      },
      {
        userId: 48,
        email: 'raquel.leon@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Raquel',
        firstSurname: 'Leon',
        secondSurname: 'Valencia',
        key: 'EST2023RST123',
        createdAt: '2024-03-25T09:45:27',
        isActive: true,
        phoneNumber: '4863665481',
      },
      {
        userId: 49,
        email: 'simon.lugo@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Simon',
        firstSurname: 'Lugo',
        secondSurname: 'Alvarado',
        key: 'TUT9012UVWXY',
        createdAt: '2024-06-20T10:35:48',
        isActive: true,
        phoneNumber: '5847469972',
      },
      {
        userId: 50,
        email: 'olivia.miranda@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Olivia',
        firstSurname: 'Miranda',
        secondSurname: 'Guevara',
        key: 'EST2023UVW456',
        createdAt: '2024-04-12T11:50:22',
        isActive: true,
        phoneNumber: '2028945279',
      },
      {
        userId: 51,
        email: 'carlos.martinez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Carlos',
        firstSurname: 'Martinez',
        secondSurname: 'Flores',
        key: 'TUT5432MNOPQ',
        createdAt: '2024-07-01T08:15:22',
        isActive: true,
        phoneNumber: '7266558874',
      },
      {
        userId: 52,
        email: 'maria.fernandez@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Maria',
        firstSurname: 'Fernandez',
        secondSurname: 'Gutierrez',
        key: 'EST2023XYZ789',
        createdAt: '2024-03-05T09:30:45',
        isActive: true,
        phoneNumber: '4411560772',
      },
      {
        userId: 53,
        email: 'juan.gonzalez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Juan',
        firstSurname: 'Gonzalez',
        secondSurname: 'Herrera',
        key: 'TUT8765RSTUV',
        createdAt: '2024-06-10T10:45:30',
        isActive: true,
        phoneNumber: '5491501272',
      },
      {
        userId: 54,
        email: 'ana.morales@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Ana',
        firstSurname: 'Morales',
        secondSurname: 'Castillo',
        key: 'EST2023DEF123',
        createdAt: '2024-04-15T11:20:15',
        isActive: true,
        phoneNumber: '5528086892',
      },
      {
        userId: 55,
        email: 'roberto.navarro@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Roberto',
        firstSurname: 'Navarro',
        secondSurname: 'Mendoza',
        key: 'TUT1098WXYZA',
        createdAt: '2024-07-05T12:35:33',
        isActive: true,
        phoneNumber: '6032341317',
      },
      {
        userId: 56,
        email: 'carmen.vega@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Carmen',
        firstSurname: 'Vega',
        secondSurname: 'Sanchez',
        key: 'EST2023GHI456',
        createdAt: '2024-03-20T13:40:40',
        isActive: true,
        phoneNumber: '4602720222',
      },
      {
        userId: 57,
        email: 'miguel.jimenez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Miguel',
        firstSurname: 'Jimenez',
        secondSurname: 'Torres',
        key: 'TUT4321BCDEF',
        createdAt: '2024-06-25T14:50:22',
        isActive: true,
        phoneNumber: '3873300068',
      },
      {
        userId: 58,
        email: 'laura.romero@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Laura',
        firstSurname: 'Romero',
        secondSurname: 'Garcia',
        key: 'EST2023JKL789',
        createdAt: '2024-04-30T15:15:18',
        isActive: false,
        phoneNumber: '7422844089',
      },
      {
        userId: 59,
        email: 'pedro.vargas@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Pedro',
        firstSurname: 'Vargas',
        secondSurname: 'Diaz',
        key: 'TUT7654GHIJK',
        createdAt: '2024-07-10T08:30:45',
        isActive: true,
        phoneNumber: '9446784269',
      },
      {
        userId: 60,
        email: 'sofia.rojas@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Sofia',
        firstSurname: 'Rojas',
        secondSurname: 'Alvarez',
        key: 'EST2023MNO123',
        createdAt: '2024-03-15T09:45:33',
        isActive: true,
        phoneNumber: '2627832430',
      },
      {
        userId: 61,
        email: 'javier.castro@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Javier',
        firstSurname: 'Castro',
        secondSurname: 'Hernandez',
        key: 'TUT0987LMNOP',
        createdAt: '2024-06-20T10:50:20',
        isActive: true,
        phoneNumber: '8567877309',
      },
      {
        userId: 62,
        email: 'elena.flores@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Elena',
        firstSurname: 'Flores',
        secondSurname: 'Moreno',
        key: 'EST2023PQR456',
        createdAt: '2024-04-05T11:25:48',
        isActive: true,
        phoneNumber: '6110077694',
      },
      {
        userId: 63,
        email: 'david.mendoza@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'David',
        firstSurname: 'Mendoza',
        secondSurname: 'Ramos',
        key: 'TUT3210QRSTU',
        createdAt: '2024-07-15T12:40:15',
        isActive: true,
        phoneNumber: '9585699396',
      },
      {
        userId: 64,
        email: 'patricia.aguilar@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Patricia',
        firstSurname: 'Aguilar',
        secondSurname: 'Vazquez',
        key: 'EST2023STU789',
        createdAt: '2024-03-25T13:15:33',
        isActive: true,
        phoneNumber: '8720997223',
      },
      {
        userId: 65,
        email: 'alejandro.ortega@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Alejandro',
        firstSurname: 'Ortega',
        secondSurname: 'Reyes',
        key: 'TUT6543VWXYZ',
        createdAt: '2024-06-30T14:30:40',
        isActive: true,
        phoneNumber: '6789898441',
      },
      {
        userId: 66,
        email: 'monica.campos@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Monica',
        firstSurname: 'Campos',
        secondSurname: 'Gutierrez',
        key: 'EST2023VWX123',
        createdAt: '2024-04-10T15:45:22',
        isActive: true,
        phoneNumber: '5263053266',
      },
      {
        userId: 67,
        email: 'raul.duran@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Raul',
        firstSurname: 'Duran',
        secondSurname: 'Castillo',
        key: 'TUT2109ABCDE',
        createdAt: '2024-07-20T08:20:48',
        isActive: false,
        phoneNumber: '7774956771',
      },
      {
        userId: 68,
        email: 'lucia.delgado@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Lucia',
        firstSurname: 'Delgado',
        secondSurname: 'Santos',
        key: 'EST2023YZA456',
        createdAt: '2024-03-30T09:35:15',
        isActive: true,
        phoneNumber: '4527618279',
      },
      {
        userId: 69,
        email: 'sergio.fuentes@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Sergio',
        firstSurname: 'Fuentes',
        secondSurname: 'Ortiz',
        key: 'TUT5432FGHIJ',
        createdAt: '2024-06-15T10:50:33',
        isActive: true,
        phoneNumber: '3421569341',
      },
      {
        userId: 70,
        email: 'daniela.espinoza@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Daniela',
        firstSurname: 'Espinoza',
        secondSurname: 'Miranda',
        key: 'EST2023BCD789',
        createdAt: '2024-04-20T11:40:20',
        isActive: true,
        phoneNumber: '8094982835',
      },
      {
        userId: 71,
        email: 'alberto.herrera@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Alberto',
        firstSurname: 'Herrera',
        secondSurname: 'Cruz',
        key: 'TUT8765KLMNO',
        createdAt: '2024-07-25T12:15:48',
        isActive: true,
        phoneNumber: '3475896066',
      },
      {
        userId: 72,
        email: 'veronica.rios@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Veronica',
        firstSurname: 'Rios',
        secondSurname: 'Mendez',
        key: 'EST2023EFG123',
        createdAt: '2024-03-10T13:30:22',
        isActive: true,
        phoneNumber: '3308138192',
      },
      {
        userId: 73,
        email: 'francisco.acosta@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Francisco',
        firstSurname: 'Acosta',
        secondSurname: 'Nunez',
        key: 'TUT1098PQRST',
        createdAt: '2024-06-05T14:45:15',
        isActive: true,
        phoneNumber: '7930447965',
      },
      {
        userId: 74,
        email: 'isabela.medina@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Isabela',
        firstSurname: 'Medina',
        secondSurname: 'Silva',
        key: 'EST2023HIJ456',
        createdAt: '2024-04-25T15:20:40',
        isActive: true,
        phoneNumber: '6971924195',
      },
      {
        userId: 75,
        email: 'gabriel.cordero@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Gabriel',
        firstSurname: 'Cordero',
        secondSurname: 'Flores',
        key: 'TUT4321UVWXY',
        createdAt: '2024-07-30T08:35:33',
        isActive: true,
        phoneNumber: '4811820786',
      },
      {
        userId: 76,
        email: 'adriana.paredes@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Adriana',
        firstSurname: 'Paredes',
        secondSurname: 'Rojas',
        key: 'EST2023KLM789',
        createdAt: '2024-03-15T09:50:18',
        isActive: false,
        phoneNumber: '7076674160',
      },
      {
        userId: 77,
        email: 'hector.salazar@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Hector',
        firstSurname: 'Salazar',
        secondSurname: 'Vargas',
        key: 'TUT7654ZABCD',
        createdAt: '2024-06-10T10:15:45',
        isActive: true,
        phoneNumber: '5375018662',
      },
      {
        userId: 78,
        email: 'claudia.vidal@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Claudia',
        firstSurname: 'Vidal',
        secondSurname: 'Molina',
        key: 'EST2023NOP123',
        createdAt: '2024-05-05T11:30:30',
        isActive: true,
        phoneNumber: '2622897218',
      },
      {
        userId: 79,
        email: 'jorge.cabrera@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Jorge',
        firstSurname: 'Cabrera',
        secondSurname: 'Guzman',
        key: 'TUT0987EFGHI',
        createdAt: '2024-08-01T12:45:22',
        isActive: true,
        phoneNumber: '6166897903',
      },
      {
        userId: 80,
        email: 'alicia.soto@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Alicia',
        firstSurname: 'Soto',
        secondSurname: 'Estrada',
        key: 'EST2023QRS456',
        createdAt: '2024-03-20T13:15:48',
        isActive: true,
        phoneNumber: '1795142796',
      },
      {
        userId: 81,
        email: 'ernesto.ponce@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Ernesto',
        firstSurname: 'Ponce',
        secondSurname: 'Cano',
        key: 'TUT3210JKLMN',
        createdAt: '2024-06-25T14:30:15',
        isActive: true,
        phoneNumber: '4283618015',
      },
      {
        userId: 82,
        email: 'natalia.montes@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Natalia',
        firstSurname: 'Montes',
        secondSurname: 'Palacios',
        key: 'EST2023TUV789',
        createdAt: '2024-05-10T15:45:33',
        isActive: true,
        phoneNumber: '8097874070',
      },
      {
        userId: 83,
        email: 'oscar.ochoa@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Oscar',
        firstSurname: 'Ochoa',
        secondSurname: 'Aguirre',
        key: 'TUT6543OPQRS',
        createdAt: '2024-08-05T08:20:40',
        isActive: true,
        phoneNumber: '4341503952',
      },
      {
        userId: 84,
        email: 'beatriz.valle@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Beatriz',
        firstSurname: 'Valle',
        secondSurname: 'Cortes',
        key: 'EST2023WXY123',
        createdAt: '2024-03-25T09:35:22',
        isActive: true,
        phoneNumber: '7008976156',
      },
      {
        userId: 85,
        email: 'manuel.arce@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Manuel',
        firstSurname: 'Arce',
        secondSurname: 'Villegas',
        key: 'TUT2109TUVWX',
        createdAt: '2024-06-30T10:50:48',
        isActive: true,
        phoneNumber: '6232294422',
      },
      {
        userId: 86,
        email: 'diana.salgado@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Diana',
        firstSurname: 'Salgado',
        secondSurname: 'Rivas',
        key: 'EST2023ZAB456',
        createdAt: '2024-05-15T11:15:15',
        isActive: true,
        phoneNumber: '3315997604',
      },
      {
        userId: 87,
        email: 'julio.pineda@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Julio',
        firstSurname: 'Pineda',
        secondSurname: 'Carrillo',
        key: 'TUT5432YABCDEF',
        createdAt: '2024-08-10T12:30:33',
        isActive: false,
        phoneNumber: '7419557175',
      },
      {
        userId: 88,
        email: 'valeria.rosales@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Valeria',
        firstSurname: 'Rosales',
        secondSurname: 'Escobar',
        key: 'EST2023CDE789',
        createdAt: '2024-03-30T13:45:20',
        isActive: true,
        phoneNumber: '5366174964',
      },
      {
        userId: 89,
        email: 'ramon.morales@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Ramon',
        firstSurname: 'Morales',
        secondSurname: 'Calderon',
        key: 'TUT8765GHIJKL',
        createdAt: '2024-07-05T14:20:45',
        isActive: true,
        phoneNumber: '3760871121',
      },
      {
        userId: 90,
        email: 'cristina.huerta@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Cristina',
        firstSurname: 'Huerta',
        secondSurname: 'Pacheco',
        key: 'EST2023FGH123',
        createdAt: '2024-05-20T15:35:18',
        isActive: true,
        phoneNumber: '4210319148',
      },
      {
        userId: 91,
        email: 'martin.luna@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Martin',
        firstSurname: 'Luna',
        secondSurname: 'Solis',
        key: 'TUT1098MNOPQR',
        createdAt: '2024-08-15T08:50:33',
        isActive: true,
        phoneNumber: '5505943588',
      },
      {
        userId: 92,
        email: 'lorena.andrade@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Lorena',
        firstSurname: 'Andrade',
        secondSurname: 'Pineda',
        key: 'EST2023IJK456',
        createdAt: '2024-03-05T09:15:48',
        isActive: true,
        phoneNumber: '4373865954',
      },
      {
        userId: 93,
        email: 'rafael.galvan@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Rafael',
        firstSurname: 'Galvan',
        secondSurname: 'Benitez',
        key: 'TUT4321STUVW',
        createdAt: '2024-07-10T10:30:22',
        isActive: true,
        phoneNumber: '7835374479',
      },
      {
        userId: 94,
        email: 'susana.mejia@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Susana',
        firstSurname: 'Mejia',
        secondSurname: 'Rangel',
        key: 'EST2023LMN789',
        createdAt: '2024-05-25T11:45:15',
        isActive: true,
        phoneNumber: '4023695853',
      },
      {
        userId: 95,
        email: 'fernando.gallegos@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Fernando',
        firstSurname: 'Gallegos',
        secondSurname: 'Avila',
        key: 'TUT7654XYZABC',
        createdAt: '2024-08-20T12:20:40',
        isActive: true,
        phoneNumber: '5390160697',
      },
      {
        userId: 96,
        email: 'martha.zamora@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Martha',
        firstSurname: 'Zamora',
        secondSurname: 'Arellano',
        key: 'EST2023OPQ123',
        createdAt: '2024-03-10T13:35:33',
        isActive: true,
        phoneNumber: '5886212780',
      },
      {
        userId: 97,
        email: 'arturo.cervantes@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Arturo',
        firstSurname: 'Cervantes',
        secondSurname: 'Montes',
        key: 'TUT0987DEFGHI',
        createdAt: '2024-07-15T14:50:18',
        isActive: true,
        phoneNumber: '7526797782',
      },
      {
        userId: 98,
        email: 'raquel.valencia@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Raquel',
        firstSurname: 'Valencia',
        secondSurname: 'Leon',
        key: 'EST2023RST456',
        createdAt: '2024-05-30T15:15:45',
        isActive: false,
        phoneNumber: '5951330757',
      },
      {
        userId: 99,
        email: 'simon.alvarado@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Simon',
        firstSurname: 'Alvarado',
        secondSurname: 'Lugo',
        key: 'TUT3210JKLMNO',
        createdAt: '2024-08-25T08:30:33',
        isActive: true,
        phoneNumber: '6145431110',
      },
      {
        userId: 100,
        email: 'olivia.guevara@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Olivia',
        firstSurname: 'Guevara',
        secondSurname: 'Miranda',
        key: 'EST2023UVW789',
        createdAt: '2024-03-15T09:45:20',
        isActive: true,
        phoneNumber: '5322704954',
      },
      {
        userId: 101,
        email: 'carlos.lopez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Carlos',
        firstSurname: 'Lopez',
        secondSurname: 'Ramirez',
        key: 'TUT6543PQRSTU',
        createdAt: '2024-07-20T10:20:48',
        isActive: true,
        phoneNumber: '1631612377',
      },
      {
        userId: 102,
        email: 'maria.gonzalez@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Maria',
        firstSurname: 'Gonzalez',
        secondSurname: 'Torres',
        key: 'EST2023XYZ123',
        createdAt: '2024-06-05T11:35:15',
        isActive: true,
        phoneNumber: '9481663910',
      },
      {
        userId: 103,
        email: 'juan.martinez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Juan',
        firstSurname: 'Martinez',
        secondSurname: 'Rodriguez',
        key: 'TUT2109VWXYZ',
        createdAt: '2024-08-30T12:50:33',
        isActive: true,
        phoneNumber: '1331631183',
      },
    ];
  }
}
