import { Injectable } from '@angular/core';
import { User } from '../models/user.model';

@Injectable({
  providedIn: 'root',
})
export class UsersTestService {
  getData(): User[] {
    return [
      {
        userId: 1001,
        email: 'carmen.lopez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Carmen',
        firstSurname: 'López',
        secondSurname: 'Martínez',
        employeeCode: 'T2023-101',
        createdAt: '2023-05-12T09:30:45Z',
        isActive: true,
      },
      {
        userId: 1002,
        email: 'miguel.garcia@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Miguel',
        firstSurname: 'García',
        secondSurname: 'Sánchez',
        studentCode: 'EST-32145',
        createdAt: '2023-06-15T14:22:10Z',
        isActive: true,
      },
      {
        userId: 1003,
        email: 'alejandro.ruiz@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Alejandro',
        firstSurname: 'Ruiz',
        secondSurname: 'Fernández',
        employeeCode: 'T2022-089',
        createdAt: '2022-09-01T08:15:30Z',
        isActive: true,
      },
      {
        userId: 1004,
        email: 'laura.moreno@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Laura',
        firstSurname: 'Moreno',
        secondSurname: 'Jiménez',
        studentCode: 'EST-45678',
        createdAt: '2023-08-20T10:45:22Z',
        isActive: true,
      },
      {
        userId: 1005,
        email: 'javier.torres@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Javier',
        firstSurname: 'Torres',
        secondSurname: 'Molina',
        studentCode: 'EST-78932',
        createdAt: '2023-07-05T11:30:15Z',
        isActive: true,
      },
      {
        userId: 1006,
        email: 'patricia.navarro@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Patricia',
        firstSurname: 'Navarro',
        secondSurname: 'López',
        employeeCode: 'T2021-056',
        createdAt: '2021-11-10T15:45:30Z',
        isActive: true,
      },
      {
        userId: 1007,
        email: 'daniel.castro@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Daniel',
        firstSurname: 'Castro',
        secondSurname: 'Vargas',
        studentCode: 'EST-10293',
        createdAt: '2023-09-12T08:20:45Z',
        isActive: true,
      },
      {
        userId: 1008,
        email: 'maria.ortiz@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'María',
        firstSurname: 'Ortiz',
        secondSurname: 'Serrano',
        employeeCode: 'T2022-124',
        createdAt: '2022-10-05T09:15:30Z',
        isActive: true,
      },
      {
        userId: 1009,
        email: 'david.ramos@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'David',
        firstSurname: 'Ramos',
        secondSurname: 'Gutiérrez',
        studentCode: 'EST-54321',
        createdAt: '2023-08-30T16:10:20Z',
        isActive: true,
      },
      {
        userId: 1010,
        email: 'ana.diaz@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Ana',
        firstSurname: 'Díaz',
        secondSurname: 'Muñoz',
        studentCode: 'EST-67890',
        createdAt: '2023-07-25T13:40:55Z',
        isActive: true,
      },
      {
        userId: 1011,
        email: 'pablo.gutierrez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Pablo',
        firstSurname: 'Gutiérrez',
        secondSurname: 'Prieto',
        employeeCode: 'T2023-078',
        createdAt: '2023-02-15T10:20:15Z',
        isActive: true,
      },
      {
        userId: 1012,
        email: 'elena.rodriguez@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Elena',
        firstSurname: 'Rodríguez',
        secondSurname: 'Casado',
        studentCode: 'EST-24680',
        createdAt: '2023-09-05T11:25:40Z',
        isActive: false,
      },
      {
        userId: 1013,
        email: 'sergio.hernandez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Sergio',
        firstSurname: 'Hernández',
        secondSurname: 'Pascual',
        employeeCode: 'T2021-045',
        createdAt: '2021-08-20T14:30:25Z',
        isActive: true,
      },
      {
        userId: 1014,
        email: 'lucia.santos@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Lucía',
        firstSurname: 'Santos',
        secondSurname: 'Blanco',
        studentCode: 'EST-13579',
        createdAt: '2023-06-28T09:50:15Z',
        isActive: true,
      },
      {
        userId: 1015,
        email: 'alberto.martinez@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Alberto',
        firstSurname: 'Martínez',
        secondSurname: 'Flores',
        studentCode: 'EST-97531',
        createdAt: '2023-08-10T15:35:20Z',
        isActive: true,
      },
      {
        userId: 1016,
        email: 'marta.perez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Marta',
        firstSurname: 'Pérez',
        secondSurname: 'Castro',
        employeeCode: 'T2022-112',
        createdAt: '2022-04-12T11:15:30Z',
        isActive: true,
      },
      {
        userId: 1017,
        email: 'roberto.gomez@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Roberto',
        firstSurname: 'Gómez',
        secondSurname: 'Vega',
        studentCode: 'EST-86420',
        createdAt: '2023-07-18T13:25:40Z',
        isActive: true,
      },
      {
        userId: 1018,
        email: 'silvia.morales@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Silvia',
        firstSurname: 'Morales',
        secondSurname: 'Romero',
        employeeCode: 'T2023-095',
        createdAt: '2023-01-25T16:40:10Z',
        isActive: true,
      },
      {
        userId: 1019,
        email: 'jorge.alonso@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Jorge',
        firstSurname: 'Alonso',
        secondSurname: 'Medina',
        studentCode: 'EST-74185',
        createdAt: '2023-09-22T10:15:30Z',
        isActive: true,
      },
      {
        userId: 1020,
        email: 'cristina.mendez@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Cristina',
        firstSurname: 'Méndez',
        secondSurname: 'León',
        studentCode: 'EST-96385',
        createdAt: '2023-08-15T09:30:45Z',
        isActive: true,
      },
      {
        userId: 1021,
        email: 'francisco.fuentes@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Francisco',
        firstSurname: 'Fuentes',
        secondSurname: 'Gallego',
        employeeCode: 'T2021-067',
        createdAt: '2021-12-10T13:20:35Z',
        isActive: false,
      },
      {
        userId: 1022,
        email: 'raquel.vidal@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Raquel',
        firstSurname: 'Vidal',
        secondSurname: 'Soto',
        studentCode: 'EST-25836',
        createdAt: '2023-06-05T14:45:20Z',
        isActive: true,
      },
      {
        userId: 1023,
        email: 'carlos.iglesias@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Carlos',
        firstSurname: 'Iglesias',
        secondSurname: 'Rojas',
        employeeCode: 'T2022-135',
        createdAt: '2022-07-22T10:40:15Z',
        isActive: true,
      },
      {
        userId: 1024,
        email: 'andrea.ruiz@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Andrea',
        firstSurname: 'Ruiz',
        secondSurname: 'Molina',
        studentCode: 'EST-36914',
        createdAt: '2023-09-18T11:35:50Z',
        isActive: true,
      },
      {
        userId: 1025,
        email: 'diego.cruz@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Diego',
        firstSurname: 'Cruz',
        secondSurname: 'Delgado',
        studentCode: 'EST-75395',
        createdAt: '2023-07-30T16:20:40Z',
        isActive: true,
      },
      {
        userId: 1026,
        email: 'beatriz.sanz@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Beatriz',
        firstSurname: 'Sanz',
        secondSurname: 'Ortega',
        employeeCode: 'T2023-108',
        createdAt: '2023-03-05T09:25:15Z',
        isActive: true,
      },
      {
        userId: 1027,
        email: 'alejandra.lara@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Alejandra',
        firstSurname: 'Lara',
        secondSurname: 'Ponce',
        studentCode: 'EST-15975',
        createdAt: '2023-08-12T14:10:30Z',
        isActive: true,
      },
      {
        userId: 1028,
        email: 'marcos.gil@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Marcos',
        firstSurname: 'Gil',
        secondSurname: 'Aguilar',
        employeeCode: 'T2022-089',
        createdAt: '2022-05-18T15:30:40Z',
        isActive: true,
      },
      {
        userId: 1029,
        email: 'julia.ferrer@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Julia',
        firstSurname: 'Ferrer',
        secondSurname: 'Duarte',
        studentCode: 'EST-95175',
        createdAt: '2023-09-10T10:45:20Z',
        isActive: true,
      },
      {
        userId: 1030,
        email: 'hugo.castro@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Hugo',
        firstSurname: 'Castro',
        secondSurname: 'Herrero',
        studentCode: 'EST-78945',
        createdAt: '2023-07-15T13:50:25Z',
        isActive: false,
      },
      {
        userId: 1031,
        email: 'monica.reyes@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Mónica',
        firstSurname: 'Reyes',
        secondSurname: 'Mendoza',
        employeeCode: 'T2021-072',
        createdAt: '2021-10-20T11:15:35Z',
        isActive: true,
      },
      {
        userId: 1032,
        email: 'gonzalo.arias@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Gonzalo',
        firstSurname: 'Arias',
        secondSurname: 'Hidalgo',
        studentCode: 'EST-35746',
        createdAt: '2023-06-22T09:40:15Z',
        isActive: true,
      },
      {
        userId: 1033,
        email: 'natalia.cobos@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Natalia',
        firstSurname: 'Cobos',
        secondSurname: 'Jiménez',
        employeeCode: 'T2022-142',
        createdAt: '2022-08-15T14:25:50Z',
        isActive: true,
      },
      {
        userId: 1034,
        email: 'victor.mora@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Víctor',
        firstSurname: 'Mora',
        secondSurname: 'Caballero',
        studentCode: 'EST-64297',
        createdAt: '2023-09-25T10:30:45Z',
        isActive: true,
      },
      {
        userId: 1035,
        email: 'carolina.salas@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Carolina',
        firstSurname: 'Salas',
        secondSurname: 'Vicente',
        studentCode: 'EST-87123',
        createdAt: '2023-08-05T15:15:30Z',
        isActive: true,
      },
      {
        userId: 1036,
        email: 'ignacio.pastor@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Ignacio',
        firstSurname: 'Pastor',
        secondSurname: 'Carmona',
        employeeCode: 'T2023-118',
        createdAt: '2023-04-10T09:35:25Z',
        isActive: true,
      },
      {
        userId: 1037,
        email: 'paula.guzman@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Paula',
        firstSurname: 'Guzmán',
        secondSurname: 'Esteban',
        studentCode: 'EST-42685',
        createdAt: '2023-07-08T11:40:20Z',
        isActive: true,
      },
      {
        userId: 1038,
        email: 'eduardo.herrera@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Eduardo',
        firstSurname: 'Herrera',
        secondSurname: 'Sánchez',
        employeeCode: 'T2022-097',
        createdAt: '2022-06-25T16:20:35Z',
        isActive: false,
      },
      {
        userId: 1039,
        email: 'marina.leon@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Marina',
        firstSurname: 'León',
        secondSurname: 'Navarro',
        studentCode: 'EST-53769',
        createdAt: '2023-09-15T13:25:40Z',
        isActive: true,
      },
      {
        userId: 1040,
        email: 'fernando.rivas@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Fernando',
        firstSurname: 'Rivas',
        secondSurname: 'Montes',
        studentCode: 'EST-19874',
        createdAt: '2023-08-22T09:50:15Z',
        isActive: true,
      },
      {
        userId: 1041,
        email: 'isabel.carrasco@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Isabel',
        firstSurname: 'Carrasco',
        secondSurname: 'Valle',
        employeeCode: 'T2021-084',
        createdAt: '2021-09-15T10:30:25Z',
        isActive: true,
      },
      {
        userId: 1042,
        email: 'adrian.serrano@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Adrián',
        firstSurname: 'Serrano',
        secondSurname: 'Rubio',
        studentCode: 'EST-65432',
        createdAt: '2023-06-30T14:15:35Z',
        isActive: true,
      },
      {
        userId: 1043,
        email: 'luz.delgado@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Luz',
        firstSurname: 'Delgado',
        secondSurname: 'Cano',
        employeeCode: 'T2022-155',
        createdAt: '2022-11-10T15:40:50Z',
        isActive: true,
      },
      {
        userId: 1044,
        email: 'samuel.pardo@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Samuel',
        firstSurname: 'Pardo',
        secondSurname: 'Prieto',
        studentCode: 'EST-75318',
        createdAt: '2023-09-28T11:20:40Z',
        isActive: true,
      },
      {
        userId: 1045,
        email: 'teresa.bravo@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Teresa',
        firstSurname: 'Bravo',
        secondSurname: 'Moya',
        studentCode: 'EST-92468',
        createdAt: '2023-07-20T16:35:25Z',
        isActive: true,
      },
      {
        userId: 1046,
        email: 'antonio.crespo@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Antonio',
        firstSurname: 'Crespo',
        secondSurname: 'Guerrero',
        employeeCode: 'T2023-126',
        createdAt: '2023-01-15T09:10:20Z',
        isActive: true,
      },
      {
        userId: 1047,
        email: 'laura.benitez@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Laura',
        firstSurname: 'Benítez',
        secondSurname: 'Vega',
        studentCode: 'EST-14725',
        createdAt: '2023-08-18T10:55:30Z',
        isActive: true,
      },
      {
        userId: 1048,
        email: 'raul.santana@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Raúl',
        firstSurname: 'Santana',
        secondSurname: 'Paredes',
        employeeCode: 'T2022-108',
        createdAt: '2022-03-22T13:45:55Z',
        isActive: true,
      },
      {
        userId: 1049,
        email: 'clara.duran@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Clara',
        firstSurname: 'Durán',
        secondSurname: 'Ramos',
        studentCode: 'EST-85297',
        createdAt: '2023-09-05T09:30:15Z',
        isActive: true,
      },
      {
        userId: 1050,
        email: 'enrique.robles@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Enrique',
        firstSurname: 'Robles',
        secondSurname: 'Cordero',
        studentCode: 'EST-36985',
        createdAt: '2023-07-12T15:25:40Z',
        isActive: false,
      },
      {
        userId: 1051,
        email: 'carlos.mendoza@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Carlos',
        firstSurname: 'Mendoza',
        secondSurname: 'Velasco',
        employeeCode: 'T2022-165',
        createdAt: '2022-05-18T09:45:30Z',
        isActive: true,
      },
      {
        userId: 1052,
        email: 'ana.torres@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Ana',
        firstSurname: 'Torres',
        secondSurname: 'Gómez',
        studentCode: 'EST-24680',
        createdAt: '2023-06-25T14:20:15Z',
        isActive: true,
      },
      {
        userId: 1053,
        email: 'miguel.flores@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Miguel',
        firstSurname: 'Flores',
        secondSurname: 'Castillo',
        studentCode: 'EST-75319',
        createdAt: '2023-07-12T10:35:45Z',
        isActive: true,
      },
      {
        userId: 1054,
        email: 'laura.vazquez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Laura',
        firstSurname: 'Vázquez',
        secondSurname: 'Ortiz',
        employeeCode: 'T2023-132',
        createdAt: '2023-02-10T11:15:25Z',
        isActive: true,
      },
      {
        userId: 1055,
        email: 'javier.marquez@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Javier',
        firstSurname: 'Márquez',
        secondSurname: 'Pérez',
        studentCode: 'EST-36914',
        createdAt: '2023-08-05T15:40:20Z',
        isActive: true,
      },
      {
        userId: 1056,
        email: 'carmen.gallego@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Carmen',
        firstSurname: 'Gallego',
        secondSurname: 'Ruiz',
        employeeCode: 'T2021-092',
        createdAt: '2021-11-15T16:30:40Z',
        isActive: true,
      },
      {
        userId: 1057,
        email: 'daniel.medina@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Daniel',
        firstSurname: 'Medina',
        secondSurname: 'Navarro',
        studentCode: 'EST-95175',
        createdAt: '2023-09-18T09:25:35Z',
        isActive: false,
      },
      {
        userId: 1058,
        email: 'patricia.blanco@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Patricia',
        firstSurname: 'Blanco',
        secondSurname: 'Guerra',
        employeeCode: 'T2022-118',
        createdAt: '2022-08-20T10:45:15Z',
        isActive: true,
      },
      {
        userId: 1059,
        email: 'alejandro.santos@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Alejandro',
        firstSurname: 'Santos',
        secondSurname: 'Díaz',
        studentCode: 'EST-14725',
        createdAt: '2023-07-30T13:50:25Z',
        isActive: true,
      },
      {
        userId: 1060,
        email: 'maria.guerrero@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'María',
        firstSurname: 'Guerrero',
        secondSurname: 'Lozano',
        studentCode: 'EST-36825',
        createdAt: '2023-08-22T11:30:45Z',
        isActive: true,
      },
      {
        userId: 1061,
        email: 'pablo.calvo@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Pablo',
        firstSurname: 'Calvo',
        secondSurname: 'Ferrer',
        employeeCode: 'T2023-140',
        createdAt: '2023-03-15T14:20:35Z',
        isActive: true,
      },
      {
        userId: 1062,
        email: 'elena.milan@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Elena',
        firstSurname: 'Milán',
        secondSurname: 'Castro',
        studentCode: 'EST-58264',
        createdAt: '2023-09-10T09:15:30Z',
        isActive: true,
      },
      {
        userId: 1063,
        email: 'sergio.dominguez@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Sergio',
        firstSurname: 'Domínguez',
        secondSurname: 'Sanz',
        employeeCode: 'T2021-075',
        createdAt: '2021-10-05T15:35:50Z',
        isActive: true,
      },
      {
        userId: 1064,
        email: 'lucia.vega@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Lucía',
        firstSurname: 'Vega',
        secondSurname: 'Mora',
        studentCode: 'EST-97531',
        createdAt: '2023-06-18T10:40:15Z',
        isActive: true,
      },
      {
        userId: 1065,
        email: 'alberto.campos@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Alberto',
        firstSurname: 'Campos',
        secondSurname: 'Ferrer',
        studentCode: 'EST-25836',
        createdAt: '2023-07-25T16:20:40Z',
        isActive: true,
      },
      {
        userId: 1066,
        email: 'marta.sierra@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Marta',
        firstSurname: 'Sierra',
        secondSurname: 'Cano',
        employeeCode: 'T2022-130',
        createdAt: '2022-04-25T11:10:25Z',
        isActive: true,
      },
      {
        userId: 1067,
        email: 'roberto.pastor@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Roberto',
        firstSurname: 'Pastor',
        secondSurname: 'Soto',
        studentCode: 'EST-69147',
        createdAt: '2023-08-15T13:25:35Z',
        isActive: true,
      },
      {
        userId: 1068,
        email: 'silvia.palacios@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Silvia',
        firstSurname: 'Palacios',
        secondSurname: 'Reyes',
        employeeCode: 'T2023-105',
        createdAt: '2023-01-20T15:45:10Z',
        isActive: false,
      },
      {
        userId: 1069,
        email: 'jorge.martos@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Jorge',
        firstSurname: 'Martos',
        secondSurname: 'Luna',
        studentCode: 'EST-47582',
        createdAt: '2023-09-22T09:35:20Z',
        isActive: true,
      },
      {
        userId: 1070,
        email: 'cristina.hidalgo@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Cristina',
        firstSurname: 'Hidalgo',
        secondSurname: 'Vargas',
        studentCode: 'EST-15935',
        createdAt: '2023-07-08T14:10:30Z',
        isActive: true,
      },
      {
        userId: 1071,
        email: 'francisco.cortes@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Francisco',
        firstSurname: 'Cortés',
        secondSurname: 'Pardo',
        employeeCode: 'T2021-088',
        createdAt: '2021-12-12T10:30:20Z',
        isActive: true,
      },
      {
        userId: 1072,
        email: 'raquel.paz@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Raquel',
        firstSurname: 'Paz',
        secondSurname: 'Pacheco',
        studentCode: 'EST-36914',
        createdAt: '2023-06-30T15:15:40Z',
        isActive: true,
      },
      {
        userId: 1073,
        email: 'carlos.rey@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Carlos',
        firstSurname: 'Rey',
        secondSurname: 'Benítez',
        employeeCode: 'T2022-145',
        createdAt: '2022-07-15T11:40:25Z',
        isActive: true,
      },
      {
        userId: 1074,
        email: 'andrea.cardenas@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Andrea',
        firstSurname: 'Cárdenas',
        secondSurname: 'Vidal',
        studentCode: 'EST-28463',
        createdAt: '2023-09-12T14:25:35Z',
        isActive: true,
      },
      {
        userId: 1075,
        email: 'diego.salazar@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Diego',
        firstSurname: 'Salazar',
        secondSurname: 'Herrera',
        studentCode: 'EST-75395',
        createdAt: '2023-08-28T10:20:15Z',
        isActive: true,
      },
      {
        userId: 1076,
        email: 'beatriz.carmona@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Beatriz',
        firstSurname: 'Carmona',
        secondSurname: 'Soto',
        employeeCode: 'T2023-115',
        createdAt: '2023-03-30T16:10:35Z',
        isActive: true,
      },
      {
        userId: 1077,
        email: 'alejandra.casado@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Alejandra',
        firstSurname: 'Casado',
        secondSurname: 'Rivas',
        studentCode: 'EST-95175',
        createdAt: '2023-07-20T09:45:30Z',
        isActive: true,
      },
      {
        userId: 1078,
        email: 'marcos.montenegro@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Marcos',
        firstSurname: 'Montenegro',
        secondSurname: 'García',
        employeeCode: 'T2022-103',
        createdAt: '2022-05-10T13:35:40Z',
        isActive: true,
      },
      {
        userId: 1079,
        email: 'julia.duque@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Julia',
        firstSurname: 'Duque',
        secondSurname: 'Barrios',
        studentCode: 'EST-15935',
        createdAt: '2023-09-05T15:25:20Z',
        isActive: false,
      },
      {
        userId: 1080,
        email: 'hugo.aranda@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Hugo',
        firstSurname: 'Aranda',
        secondSurname: 'Ramos',
        studentCode: 'EST-64297',
        createdAt: '2023-08-12T11:15:35Z',
        isActive: true,
      },
      {
        userId: 1081,
        email: 'monica.cabello@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Mónica',
        firstSurname: 'Cabello',
        secondSurname: 'Moreno',
        employeeCode: 'T2021-079',
        createdAt: '2021-10-22T14:40:15Z',
        isActive: true,
      },
      {
        userId: 1082,
        email: 'gonzalo.toledo@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Gonzalo',
        firstSurname: 'Toledo',
        secondSurname: 'Fuentes',
        studentCode: 'EST-37946',
        createdAt: '2023-06-15T10:55:30Z',
        isActive: true,
      },
      {
        userId: 1083,
        email: 'natalia.roman@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Natalia',
        firstSurname: 'Román',
        secondSurname: 'Pascual',
        employeeCode: 'T2022-150',
        createdAt: '2022-09-18T15:30:45Z',
        isActive: true,
      },
      {
        userId: 1084,
        email: 'victor.cuesta@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Víctor',
        firstSurname: 'Cuesta',
        secondSurname: 'Molina',
        studentCode: 'EST-85297',
        createdAt: '2023-09-28T09:20:40Z',
        isActive: true,
      },
      {
        userId: 1085,
        email: 'carolina.arroyo@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Carolina',
        firstSurname: 'Arroyo',
        secondSurname: 'Prieto',
        studentCode: 'EST-26485',
        createdAt: '2023-07-18T13:10:25Z',
        isActive: true,
      },
      {
        userId: 1086,
        email: 'ignacio.vera@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Ignacio',
        firstSurname: 'Vera',
        secondSurname: 'Aparicio',
        employeeCode: 'T2023-120',
        createdAt: '2023-02-25T16:45:35Z',
        isActive: true,
      },
      {
        userId: 1087,
        email: 'paula.navas@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Paula',
        firstSurname: 'Navas',
        secondSurname: 'Rico',
        studentCode: 'EST-46825',
        createdAt: '2023-08-05T11:30:20Z',
        isActive: true,
      },
      {
        userId: 1088,
        email: 'eduardo.leon@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Eduardo',
        firstSurname: 'León',
        secondSurname: 'Gallardo',
        employeeCode: 'T2022-115',
        createdAt: '2022-06-12T14:25:35Z',
        isActive: true,
      },
      {
        userId: 1089,
        email: 'marina.pineda@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Marina',
        firstSurname: 'Pineda',
        secondSurname: 'Sanz',
        studentCode: 'EST-19874',
        createdAt: '2023-09-15T10:15:40Z',
        isActive: true,
      },
      {
        userId: 1090,
        email: 'fernando.valdes@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Fernando',
        firstSurname: 'Valdés',
        secondSurname: 'Paredes',
        studentCode: 'EST-75395',
        createdAt: '2023-07-28T15:40:25Z',
        isActive: false,
      },
      {
        userId: 1091,
        email: 'isabel.aguado@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Isabel',
        firstSurname: 'Aguado',
        secondSurname: 'Montes',
        employeeCode: 'T2021-096',
        createdAt: '2021-09-30T11:35:15Z',
        isActive: true,
      },
      {
        userId: 1092,
        email: 'adrian.mateo@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Adrián',
        firstSurname: 'Mateo',
        secondSurname: 'Valle',
        studentCode: 'EST-58264',
        createdAt: '2023-06-20T09:50:30Z',
        isActive: true,
      },
      {
        userId: 1093,
        email: 'luz.redondo@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Luz',
        firstSurname: 'Redondo',
        secondSurname: 'Beltrán',
        employeeCode: 'T2022-160',
        createdAt: '2022-10-15T13:20:40Z',
        isActive: true,
      },
      {
        userId: 1094,
        email: 'samuel.guerrero@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Samuel',
        firstSurname: 'Guerrero',
        secondSurname: 'Espinosa',
        studentCode: 'EST-36914',
        createdAt: '2023-09-22T15:10:25Z',
        isActive: true,
      },
      {
        userId: 1095,
        email: 'teresa.marin@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Teresa',
        firstSurname: 'Marín',
        secondSurname: 'Castillo',
        studentCode: 'EST-75319',
        createdAt: '2023-08-10T10:35:15Z',
        isActive: true,
      },
      {
        userId: 1096,
        email: 'antonio.murillo@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Antonio',
        firstSurname: 'Murillo',
        secondSurname: 'Ponce',
        employeeCode: 'T2023-128',
        createdAt: '2023-04-05T14:45:35Z',
        isActive: true,
      },
      {
        userId: 1097,
        email: 'laura.ferreira@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Laura',
        firstSurname: 'Ferreira',
        secondSurname: 'Solís',
        studentCode: 'EST-15935',
        createdAt: '2023-07-15T09:30:20Z',
        isActive: true,
      },
      {
        userId: 1098,
        email: 'raul.soler@universidad.edu',
        role: {
          roleId: 'ROLE_TUTOR',
          roleName: 'Tutor',
        },
        name: 'Raúl',
        firstSurname: 'Soler',
        secondSurname: 'Miranda',
        employeeCode: 'T2022-125',
        createdAt: '2022-03-18T15:15:40Z',
        isActive: false,
      },
      {
        userId: 1099,
        email: 'clara.ribera@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Clara',
        firstSurname: 'Ribera',
        secondSurname: 'Aguilar',
        studentCode: 'EST-24680',
        createdAt: '2023-09-08T11:20:30Z',
        isActive: true,
      },
      {
        userId: 1100,
        email: 'enrique.martin@universidad.edu',
        role: {
          roleId: 'ROLE_ESTUDIANTE',
          roleName: 'Estudiante',
        },
        name: 'Enrique',
        firstSurname: 'Martín',
        secondSurname: 'Hidalgo',
        studentCode: 'EST-69147',
        createdAt: '2023-08-25T13:40:15Z',
        isActive: true,
      },
    ];
  }
}
