import { Injectable } from '@angular/core';
import { Tutor } from '../models/tutors.model';

@Injectable({
  providedIn: 'root',
})
export class TutorsTestService {
  getData(): Tutor[] {
    return [
      {
        tutorId: 1,
        name: 'María',
        firstSurname: 'González',
        secondSurname: 'López',
        employeeCode: 'EMP0123456789',
        phoneNumber: '5551234567',
        email: 'maria.gonzalez@universidad.edu',
      },
      {
        tutorId: 2,
        name: 'Carlos',
        firstSurname: 'Rodríguez',
        secondSurname: 'Martínez',
        employeeCode: 'TUTOR9876543210',
        phoneNumber: '5552345678',
        email: 'carlos.rodriguez@universidad.edu',
      },
      {
        tutorId: 3,
        name: 'Ana',
        firstSurname: 'Sánchez',
        secondSurname: 'García',
        employeeCode: 'ACAD1234567890',
        phoneNumber: '5553456789',
        email: 'ana.sanchez@universidad.edu',
      },
      {
        tutorId: 4,
        name: 'José',
        firstSurname: 'Pérez',
        secondSurname: 'Fernández',
        employeeCode: 'PROF0987654321',
        phoneNumber: '5554567890',
        email: 'jose.perez@universidad.edu',
      },
      {
        tutorId: 5,
        name: 'Laura',
        firstSurname: 'Díaz',
        secondSurname: 'Torres',
        employeeCode: 'TUTORID12345678',
        phoneNumber: '5555678901',
        email: 'laura.diaz@universidad.edu',
      },
      {
        tutorId: 6,
        name: 'Javier',
        firstSurname: 'Gómez',
        secondSurname: 'Hernández',
        employeeCode: 'ACAD8765432109',
        phoneNumber: '5556789012',
        email: 'javier.gomez@universidad.edu',
      },
      {
        tutorId: 7,
        name: 'Isabel',
        firstSurname: 'Moreno',
        secondSurname: 'Ruiz',
        employeeCode: 'EMP9876543210',
        phoneNumber: '5557890123',
        email: 'isabel.moreno@universidad.edu',
      },
      {
        tutorId: 8,
        name: 'Miguel',
        firstSurname: 'Jiménez',
        secondSurname: 'Álvarez',
        employeeCode: 'TUTORABC123456',
        phoneNumber: '5558901234',
        email: 'miguel.jimenez@universidad.edu',
      },
      {
        tutorId: 9,
        name: 'Sofía',
        firstSurname: 'López',
        secondSurname: 'Muñoz',
        employeeCode: 'DOCENTE1234567',
        phoneNumber: '5559012345',
        email: 'sofia.lopez@universidad.edu',
      },
      {
        tutorId: 10,
        name: 'David',
        firstSurname: 'Martín',
        secondSurname: 'Romero',
        employeeCode: 'PROF9876543210',
        phoneNumber: '5550123456',
        email: 'david.martin@universidad.edu',
      },
      {
        tutorId: 11,
        name: 'Elena',
        firstSurname: 'Alonso',
        secondSurname: 'Gutiérrez',
        employeeCode: 'ACAD0123456789',
        phoneNumber: '5551237890',
        email: 'elena.alonso@universidad.edu',
      },
      {
        tutorId: 12,
        name: 'Pablo',
        firstSurname: 'Navarro',
        secondSurname: 'Vázquez',
        employeeCode: 'TUTOR8765432109',
        phoneNumber: '5552348901',
        email: 'pablo.navarro@universidad.edu',
      },
      {
        tutorId: 13,
        name: 'Lucía',
        firstSurname: 'Torres',
        secondSurname: 'Serrano',
        employeeCode: 'EMP7654321098',
        phoneNumber: '5553459012',
        email: 'lucia.torres@universidad.edu',
      },
      {
        tutorId: 14,
        name: 'Roberto',
        firstSurname: 'Ramos',
        secondSurname: 'Gil',
        employeeCode: 'DOCENTE9876543',
        phoneNumber: '5554560123',
        email: 'roberto.ramos@universidad.edu',
      },
      {
        tutorId: 15,
        name: 'Patricia',
        firstSurname: 'Ortiz',
        secondSurname: 'Marín',
        employeeCode: 'PROFEABC123456',
        phoneNumber: '5555671234',
        email: 'patricia.ortiz@universidad.edu',
      },
      {
        tutorId: 16,
        name: 'Francisco',
        firstSurname: 'Molina',
        secondSurname: 'Castro',
        employeeCode: 'ACAD1029384756',
        phoneNumber: '5556782345',
        email: 'francisco.molina@universidad.edu',
      },
      {
        tutorId: 17,
        name: 'Carmen',
        firstSurname: 'Delgado',
        secondSurname: 'Ortega',
        employeeCode: 'TUTOR0192837465',
        phoneNumber: '5557893456',
        email: 'carmen.delgado@universidad.edu',
      },
      {
        tutorId: 18,
        name: 'Alejandro',
        firstSurname: 'Rubio',
        secondSurname: 'Medina',
        employeeCode: 'EMP2019384756',
        phoneNumber: '5558904567',
        email: 'alejandro.rubio@universidad.edu',
      },
      {
        tutorId: 19,
        name: 'Raquel',
        firstSurname: 'Suárez',
        secondSurname: 'Castillo',
        employeeCode: 'PROF1234509876',
        phoneNumber: '5559015678',
        email: 'raquel.suarez@universidad.edu',
      },
      {
        tutorId: 20,
        name: 'Antonio',
        firstSurname: 'Blanco',
        secondSurname: 'Prieto',
        employeeCode: 'DOCABC12345678',
        phoneNumber: '5550126789',
        email: 'antonio.blanco@universidad.edu',
      },
      {
        tutorId: 21,
        name: 'Sara',
        firstSurname: 'Fuentes',
        secondSurname: 'Méndez',
        employeeCode: 'ACAD1122334455',
        phoneNumber: '5551237890',
        email: 'sara.fuentes@universidad.edu',
      },
      {
        tutorId: 22,
        name: 'Manuel',
        firstSurname: 'Herrera',
        secondSurname: 'Núñez',
        employeeCode: 'TUTOR2233445566',
        phoneNumber: '5552348901',
        email: 'manuel.herrera@universidad.edu',
      },
      {
        tutorId: 23,
        name: 'Cristina',
        firstSurname: 'Domínguez',
        secondSurname: 'Soto',
        employeeCode: 'EMP3344556677',
        phoneNumber: '5553459012',
        email: 'cristina.dominguez@universidad.edu',
      },
      {
        tutorId: 24,
        name: 'Jorge',
        firstSurname: 'Pascual',
        secondSurname: 'Santamaría',
        employeeCode: 'PROF4455667788',
        phoneNumber: '5554560123',
        email: 'jorge.pascual@universidad.edu',
      },
      {
        tutorId: 25,
        name: 'Marta',
        firstSurname: 'Vega',
        secondSurname: 'Iglesias',
        employeeCode: 'ACAD5566778899',
        phoneNumber: '5555671234',
        email: 'marta.vega@universidad.edu',
      },
      {
        tutorId: 26,
        name: 'Alberto',
        firstSurname: 'Reyes',
        secondSurname: 'Bravo',
        employeeCode: 'TUTOR6677889900',
        phoneNumber: '5556782345',
        email: 'alberto.reyes@universidad.edu',
      },
      {
        tutorId: 27,
        name: 'Natalia',
        firstSurname: 'Campos',
        secondSurname: 'Gallego',
        employeeCode: 'EMP7788990011',
        phoneNumber: '5557893456',
        email: 'natalia.campos@universidad.edu',
      },
      {
        tutorId: 28,
        name: 'Fernando',
        firstSurname: 'Calvo',
        secondSurname: 'Herrero',
        employeeCode: 'PROF8899001122',
        phoneNumber: '5558904567',
        email: 'fernando.calvo@universidad.edu',
      },
      {
        tutorId: 29,
        name: 'Julia',
        firstSurname: 'Ibáñez',
        secondSurname: 'León',
        employeeCode: 'ACAD9900112233',
        phoneNumber: '5559015678',
        email: 'julia.ibanez@universidad.edu',
      },
      {
        tutorId: 30,
        name: 'Daniel',
        firstSurname: 'Guerrero',
        secondSurname: 'Crespo',
        employeeCode: 'TUTOR0011223344',
        phoneNumber: '5550126789',
        email: 'daniel.guerrero@universidad.edu',
      },
      {
        tutorId: 31,
        name: 'Beatriz',
        firstSurname: 'Mendoza',
        secondSurname: 'Cruz',
        employeeCode: 'EMP1122334455Z',
        phoneNumber: '5551237890',
        email: 'beatriz.mendoza@universidad.edu',
      },
      {
        tutorId: 32,
        name: 'Pedro',
        firstSurname: 'Santos',
        secondSurname: 'Rojas',
        employeeCode: 'PROF2233445566Z',
        phoneNumber: '5552348901',
        email: 'pedro.santos@universidad.edu',
      },
      {
        tutorId: 33,
        name: 'Rosa',
        firstSurname: 'Carrasco',
        secondSurname: 'Vargas',
        employeeCode: 'DOCENTE3344556677',
        phoneNumber: '5553459012',
        email: 'rosa.carrasco@universidad.edu',
      },
      {
        tutorId: 34,
        name: 'Ángel',
        firstSurname: 'Flores',
        secondSurname: 'Esteban',
        employeeCode: 'ACAD4455667788Z',
        phoneNumber: '5554560123',
        email: 'angel.flores@universidad.edu',
      },
      {
        tutorId: 35,
        name: 'Silvia',
        firstSurname: 'Benítez',
        secondSurname: 'Parra',
        employeeCode: 'TUTOR5566778899Z',
        phoneNumber: '5555671234',
        email: 'silvia.benitez@universidad.edu',
      },
      {
        tutorId: 36,
        name: 'Sergio',
        firstSurname: 'Varela',
        secondSurname: 'Mora',
        employeeCode: 'EMP6677889900Z',
        phoneNumber: '5556782345',
        email: 'sergio.varela@universidad.edu',
      },
      {
        tutorId: 37,
        name: 'Teresa',
        firstSurname: 'Aguilar',
        secondSurname: 'Vila',
        employeeCode: 'PROF7788990011Z',
        phoneNumber: '5557893456',
        email: 'teresa.aguilar@universidad.edu',
      },
      {
        tutorId: 38,
        name: 'Andrés',
        firstSurname: 'Soler',
        secondSurname: 'Moya',
        employeeCode: 'ACAD8899001122Z',
        phoneNumber: '5558904567',
        email: 'andres.soler@universidad.edu',
      },
      {
        tutorId: 39,
        name: 'Mónica',
        firstSurname: 'Velasco',
        secondSurname: 'Carmona',
        employeeCode: 'TUTOR9900112233Z',
        phoneNumber: '5559015678',
        email: 'monica.velasco@universidad.edu',
      },
      {
        tutorId: 40,
        name: 'Víctor',
        firstSurname: 'Pastor',
        secondSurname: 'Sanz',
        employeeCode: 'EMP0011223344Z',
        phoneNumber: '5550126789',
        email: 'victor.pastor@universidad.edu',
      },
      {
        tutorId: 41,
        name: 'Marina',
        firstSurname: 'Garrido',
        secondSurname: 'Luna',
        employeeCode: 'DOC12345678901',
        phoneNumber: '5551234567',
        email: 'marina.garrido@universidad.edu',
      },
      {
        tutorId: 42,
        name: 'Ricardo',
        firstSurname: 'Pardo',
        secondSurname: 'Ferrer',
        employeeCode: 'EMP12345678902',
        phoneNumber: '5552345678',
        email: 'ricardo.pardo@universidad.edu',
      },
      {
        tutorId: 43,
        name: 'Sonia',
        firstSurname: 'Bravo',
        secondSurname: 'Durán',
        employeeCode: 'TUTOR12345678903',
        phoneNumber: '5553456789',
        email: 'sonia.bravo@universidad.edu',
      },
      {
        tutorId: 44,
        name: 'Jaime',
        firstSurname: 'Gallego',
        secondSurname: 'Caballero',
        employeeCode: 'PROF12345678904',
        phoneNumber: '5554567890',
        email: 'jaime.gallego@universidad.edu',
      },
      {
        tutorId: 45,
        name: 'Alicia',
        firstSurname: 'Herrera',
        secondSurname: 'Santana',
        employeeCode: 'ACAD12345678905',
        phoneNumber: '5555678901',
        email: 'alicia.herrera@universidad.edu',
      },
      {
        tutorId: 46,
        name: 'Guillermo',
        firstSurname: 'León',
        secondSurname: 'Rivas',
        employeeCode: 'TUTOR12345678906',
        phoneNumber: '5556789012',
        email: 'guillermo.leon@universidad.edu',
      },
      {
        tutorId: 47,
        name: 'Esther',
        firstSurname: 'Vidal',
        secondSurname: 'Ríos',
        employeeCode: 'EMP12345678907',
        phoneNumber: '5557890123',
        email: 'esther.vidal@universidad.edu',
      },
      {
        tutorId: 48,
        name: 'Marcos',
        firstSurname: 'Cortés',
        secondSurname: 'Quintana',
        employeeCode: 'PROF12345678908',
        phoneNumber: '5558901234',
        email: 'marcos.cortes@universidad.edu',
      },
      {
        tutorId: 49,
        name: 'Inés',
        firstSurname: 'Hidalgo',
        secondSurname: 'Méndez',
        employeeCode: 'ACAD12345678909',
        phoneNumber: '5559012345',
        email: 'ines.hidalgo@universidad.edu',
      },
      {
        tutorId: 50,
        name: 'Joaquín',
        firstSurname: 'Ferrer',
        secondSurname: 'Salas',
        employeeCode: 'TUTOR12345678910',
        phoneNumber: '5550123456',
        email: 'joaquin.ferrer@universidad.edu',
      },
      {
        tutorId: 51,
        name: 'Raúl',
        firstSurname: 'Castaño',
        secondSurname: 'Montero',
        employeeCode: 'EMP123456789111',
        phoneNumber: '5551237890',
        email: 'raul.castano@universidad.edu',
      },
      {
        tutorId: 52,
        name: 'Nuria',
        firstSurname: 'Rey',
        secondSurname: 'Guerrero',
        employeeCode: 'PROF123456789122',
        phoneNumber: '5552348901',
        email: 'nuria.rey@universidad.edu',
      },
      {
        tutorId: 53,
        name: 'Gabriel',
        firstSurname: 'Manzano',
        secondSurname: 'Soto',
        employeeCode: 'ACAD123456789133',
        phoneNumber: '5553459012',
        email: 'gabriel.manzano@universidad.edu',
      },
      {
        tutorId: 54,
        name: 'Pilar',
        firstSurname: 'Mejía',
        secondSurname: 'Campos',
        employeeCode: 'TUTOR123456789144',
        phoneNumber: '5554560123',
        email: 'pilar.mejia@universidad.edu',
      },
      {
        tutorId: 55,
        name: 'Diego',
        firstSurname: 'Luque',
        secondSurname: 'Aguilar',
        employeeCode: 'EMP123456789155',
        phoneNumber: '5555671234',
        email: 'diego.luque@universidad.edu',
      },
      {
        tutorId: 56,
        name: 'Irene',
        firstSurname: 'Polo',
        secondSurname: 'Redondo',
        employeeCode: 'PROF123456789166',
        phoneNumber: '5556782345',
        email: 'irene.polo@universidad.edu',
      },
      {
        tutorId: 57,
        name: 'Tomás',
        firstSurname: 'Acosta',
        secondSurname: 'Beltrán',
        employeeCode: 'ACAD123456789177',
        phoneNumber: '5557893456',
        email: 'tomas.acosta@universidad.edu',
      },
      {
        tutorId: 58,
        name: 'Susana',
        firstSurname: 'Giménez',
        secondSurname: 'Arroyo',
        employeeCode: 'TUTOR123456789188',
        phoneNumber: '5558904567',
        email: 'susana.gimenez@universidad.edu',
      },
      {
        tutorId: 59,
        name: 'Salvador',
        firstSurname: 'Peña',
        secondSurname: 'Lozano',
        employeeCode: 'EMP123456789199',
        phoneNumber: '5559015678',
        email: 'salvador.pena@universidad.edu',
      },
      {
        tutorId: 60,
        name: 'Clara',
        firstSurname: 'Gracia',
        secondSurname: 'Valverde',
        employeeCode: 'PROF1234567892000',
        phoneNumber: '5550126789',
        email: 'clara.gracia@universidad.edu',
      },
      {
        tutorId: 61,
        name: 'Xavier',
        firstSurname: 'Cuesta',
        secondSurname: 'Casado',
        employeeCode: 'ACAD1234567892100',
        phoneNumber: '5551237890',
        email: 'xavier.cuesta@universidad.edu',
      },
      {
        tutorId: 62,
        name: 'Lourdes',
        firstSurname: 'Sáez',
        secondSurname: 'Bueno',
        employeeCode: 'TUTOR1234567892200',
        phoneNumber: '5552348901',
        email: 'lourdes.saez@universidad.edu',
      },
      {
        tutorId: 63,
        name: 'Ignacio',
        firstSurname: 'Soria',
        secondSurname: 'Valle',
        employeeCode: 'EMP1234567892300',
        phoneNumber: '5553459012',
        email: 'ignacio.soria@universidad.edu',
      },
      {
        tutorId: 64,
        name: 'Ainhoa',
        firstSurname: 'Cabrera',
        secondSurname: 'Vera',
        employeeCode: 'PROF1234567892400',
        phoneNumber: '5554560123',
        email: 'ainhoa.cabrera@universidad.edu',
      },
      {
        tutorId: 65,
        name: 'Héctor',
        firstSurname: 'Márquez',
        secondSurname: 'Salazar',
        employeeCode: 'ACAD1234567892500',
        phoneNumber: '5555671234',
        email: 'hector.marquez@universidad.edu',
      },
    ];
  }
}
